### ISSUE TITLE
Maker versions now 2.31.11 or 3.01.03

### ISSUE THREAD

**Issue by ckeeling** [brewsci/homebrew-bio#1004]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:

- [X] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new or https://github.com/Linuxbrew/brew/issues/new.
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
The Formula for Maker doesn't work anymore because the developers of Maker has bumped the version to 2.31.11 or 3.01.03 and removed http://yandell.topaz.genetics.utah.edu/maker_downloads/static/maker-2.31.10.tgz referred to in the formula.

**Comment by sjackman** [comment]
You should still be able to use the binary bottle. Does it work for you?

These links don't work for me.
http://yandell.topaz.genetics.utah.edu/maker_downloads/static/maker-2.31.11.tgz
http://yandell.topaz.genetics.utah.edu/maker_downloads/static/maker-3.01.03.tgz
I've e-mailed Carson to ask that he create these tarballs.

**Comment by ckeeling** [comment]
The Download links on the download page for Maker point here:
http://yandell.topaz.genetics.utah.edu/maker_downloads/FC70/C459/A8E4/EBC363AADCA005BD1CD4289C5CA6/maker-2.31.11.tgz
http://yandell.topaz.genetics.utah.edu/maker_downloads/FC70/C459/A8E4/EBC363AADCA005BD1CD4289C5CA6/maker-3.01.03.tgz

**Comment by sjackman** [comment]
I believe that's after registering, and those links are private to you.

**Comment by ckeeling** [comment]
OK, I deleted those private links from this thread. I am needing the --with-open-mpi parameter, so brew doesn't use the bottle.

**Comment by sjackman** [comment]
Ah, so the bottle builds with support for `--with-open-mpi parameter` by default. See https://github.com/brewsci/homebrew-bio/blob/124002acce2ff26c8d4a75afa11a78dcc76876a4/Formula/maker.rb#L34-L39

`brew install open-mpi maker` should do what you want.

**Comment by ckeeling** [comment]
Thanks @sjackman 

That works! I need to learn Ruby to better understand how formula are written.

```bash
brew install --with-open-mpi maker # doesn't use the bottle for maker and fails
brew install open-mpi maker # uses the bottle for maker and works
```

**Comment by sjackman** [comment]
OpenMPI support in `maker` was a unique and special case. The formula is tweaked so that `open-mpi` is installed when building the binary package on CI, but not necessarily required when the user installs it, so that it's optional for the user.
