### ISSUE TITLE
viennarna

### ISSUE THREAD

**Issue by kcygan** [brewsci/homebrew-bio#1075]
https://gist.github.com/kcygan/224e55a2dd096fa43e13a53e643c2848

**Comment by sjackman** [comment]
I'm afraid that compiling from source is not actively supported, as we don't have the time to troubleshoot individual compile errors. You may use the precompiled binary bottle by upgrading to macOS 10.15 Catalina. Alternatively, you may try installing the Catalina bottle on macOS 10.13.6 and cross your fingers.

```bash
brew install https://dl.bintray.com/linuxbrew/bottles-bio/viennarna-2.4.14.catalina.bottle.tar.gz 
```
