### ISSUE TITLE
dsh-bio, nextflow: Java 1.8+ is required to install this formula.

### ISSUE THREAD

**Issue by heuermh** [brewsci/homebrew-bio#1158]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:

- [ ] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new or https://github.com/Linuxbrew/brew/issues/new.
- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)

Install dsh-bio on a fresh Homebrew installation, after installing `openjdk` and `openjdk@11`.

- What happened (include command output)

Other JVM based applications installed fine (e.g. `maven`, `ant`, `apache-spark`, `adam`, `cannoli`) but `dsh-bio` and `nextflow` do not.  Perhaps their JVM dependency is not declared the same as these other formulae.

```
$ brew install dsh-bio
...
==> Installing dsh-bio from brewsci/bio
dsh-bio: Java 1.8+ is required to install this formula.
Install AdoptOpenJDK with Homebrew Cask:
  brew cask install adoptopenjdk
Error: An unsatisfied requirement failed this build.
```

```
$ brew install nextflow
...
==> Installing nextflow from brewsci/bio
nextflow: Java 1.8 is required to install this formula.
Install AdoptOpenJDK 8 with Homebrew Cask:
  brew cask install homebrew/cask-versions/adoptopenjdk8
Error: An unsatisfied requirement failed this build.
```

- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# Formula additions or changes

To get formulae added or changed in Brewsci/bio please file a [Pull Request](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md).

**Comment by pditommaso** [comment]
Can't see what's wrong with: 

https://github.com/brewsci/homebrew-bio/blob/develop/Formula/nextflow.rb#L17

**Comment by heuermh** [comment]
I missed adding these links before
```
$ sudo ln -sfn \
  $(brew --prefix)/opt/openjdk/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk.jdk
$ sudo ln -sfn \
  $(brew --prefix)/opt/openjdk@11/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-11.jdk
```

which fix the Apple system java scripts
```
$ export JAVA_HOME=`/usr/libexec/java_home --version 11`
$ java -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+11)
OpenJDK 64-Bit Server VM (build 11.0.8+11, mixed mode)

$ export JAVA_HOME=`/usr/libexec/java_home --version 14`
$ java -version
openjdk version "14.0.1" 2020-04-14
OpenJDK Runtime Environment (build 14.0.1+14)
OpenJDK 64-Bit Server VM (build 14.0.1+14, mixed mode, sharing)
```

but still do not allow these formulae to be installed
```
$ brew reinstall nextflow
nextflow: Java 1.8 is required to install this formula.
Install AdoptOpenJDK 8 with Homebrew Cask:
  brew cask install homebrew/cask-versions/adoptopenjdk8
Error: An unsatisfied requirement failed this build.
```

I think the `depends_on` lines might need to use `openjdk` instead of `java`, see e.g. https://discourse.brew.sh/t/depends-on-java-openjdk/7915

**Comment by sjackman** [comment]
Did `brew cask install homebrew/cask-versions/adoptopenjdk8` work for you?

**Comment by heuermh** [comment]
No, I didn't try that.  I don't know anything about `adoptopenjdk8`, and wouldn't it be a problem for something in `homebrew-bio` to depend on something in `homebrew-casks`?  That is why I am proposing to switch to `openjdk` in the two pull requests.  Neither specifically requires JDK 8 and both run fine on JDK 11+.

**Comment by sjackman** [comment]
How about `depends_on :java` instead?

**Comment by heuermh** [comment]
That might work.  I was going on the advice from the linked post above
>depends_on :java is when java 1.8 is needed which can’t be build from source on modern macOS versions and therefore uses a cask. depends_on "openjdk" is the latest java version which are build from source. If you see any formula that support a version higher than 1.8 a pull request to use depends_on "openjdk" would be welcome.

Unfortunately I won't be able to test on a fresh OSX install any more because I've since installed the Oracle JDK8 manually, which satisfies the formula build requirement.

**Comment by sjackman** [comment]
> `depends_on :java` is when java 1.8 is needed …

Ah, that is news to me! I didn't realize that the meaning of `depends_on :java` had changed from what it used to mean. Sorry for all the confusion. In that case, I'm fine with `depends_on "openjdk"`.

**Comment by sjackman** [comment]
I did like though that `depends_on :java` could make use of `/usr/bin/java` when it was sufficient. `brew install openjdk` takes 337 MB of disk space, and its dependencies take another 95 MB of disk space.

**Comment by jonchang** [comment]
Java requirements are going the way of the ivory-billed woodpecker, so see https://github.com/brewsci/homebrew-bio/pull/1213 for moving java => openjdk

**Comment by sjackman** [comment]
Thanks, Jon!
