### ISSUE TITLE
pymol error: macOS 11 or later required

### ISSUE THREAD

**Issue by 2young-2simple-sometimes-naive** [brewsci/homebrew-bio#1226]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:

- [ x ] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new or https://github.com/Linuxbrew/brew/issues/new.
- [ x ] Ran `brew update` and retried your prior step?
- [ x ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ x ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)
-- run pymol
- What happened (include command output)
--pymol first asks:`The last time you opened Python, it unexpectedly quit while reopening windows. Do you want to try to reopen its windows again?`
--if I choose `Don't Reopen`, it quits. If I choose `Reopen`, it quits with error `macOS 11 or later required`
- What you expected to happen
-- run pymol
- Step-by-step reproduction instructions (by running `brew install` commands)
--run pymol at command line

# Formula additions or changes
None
To get formulae added or changed in Brewsci/bio please file a [Pull Request](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md).
[error.log](https://github.com/brewsci/homebrew-bio/files/5762395/error.log)

[brew-config.txt](https://github.com/brewsci/homebrew-bio/files/5762396/brew-config.txt)

brew doctor gives empty output

**Comment by sjackman** [comment]
That `pymol` bottle was built on macOS Catalina 10.15. Sorry it's not working for you, but I'm not able to troubleshoot it any further.
