### ISSUE TITLE
All version-update PR are failing because of updated sha256/cellar syntax

### ISSUE THREAD

**Issue by bredelings** [brewsci/homebrew-bio#1273]
Hi,

It looks like all the version-update PRs are failing because their _dependencies_ don't have updated sha256/cellar syntax.  It seems a bit odd to blame a formula for warnings in its dependencies.

Just wondering what the plan is on this.

Thanks!
-BenRI

**Comment by sjackman** [comment]
I've merged PR https://github.com/brewsci/homebrew-bio/pull/1274 to fix the style issues.
