### ISSUE TITLE
HTTP 403 for https://archive.org bottle URLs

### ISSUE THREAD

**Issue by heuermh** [brewsci/homebrew-bio#1321]
```bash
$ brew upgrade
==> Upgrading 3 outdated packages:
brewsci/bio/cannoli 0.11.1 -> 0.12.0
brewsci/bio/dsh-bio 2.0.2 -> 2.0.3
brewsci/bio/adam 0.33.0 -> 0.34.0
==> Upgrading brewsci/bio/cannoli 0.11.1 -> 0.12.0
==> Downloading https://archive.org/download/brewsci/bottles-bio/cannoli-0.12.0.catalina.bottle.tar.gz
##O=#  #
curl: (22) The requested URL returned error: 403
Error: Failed to download resource "cannoli"
Download failed: https://archive.org/download/brewsci/bottles-bio/cannoli-0.12.0.catalina.bottle.tar.gz
==> Upgrading brewsci/bio/dsh-bio 2.0.2 -> 2.0.3
==> Downloading https://archive.org/download/brewsci/bottles-bio/dsh-bio-2.0.3.catalina.bottle.tar.gz
#=#=-#  #
curl: (22) The requested URL returned error: 403
Error: Failed to download resource "dsh-bio"
Download failed: https://archive.org/download/brewsci/bottles-bio/dsh-bio-2.0.3.catalina.bottle.tar.gz
==> Upgrading brewsci/bio/adam 0.33.0 -> 0.34.0
==> Downloading https://archive.org/download/brewsci/bottles-bio/adam-0.34.0.catalina.bottle.tar.gz
##O#- #
curl: (22) The requested URL returned error: 403
Error: Failed to download resource "adam"
Download failed: https://archive.org/download/brewsci/bottles-bio/adam-0.34.0.catalina.bottle.tar.gz

$ brew gist-logs dsh-bio
Error: No logs.

$ brew config
HOMEBREW_VERSION: 3.0.9-2-ga59d077
ORIGIN: https://github.com/Homebrew/brew
HEAD: a59d07760feaf287a80fa62730f1dfbb7d77f75f
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3ea67957004027b62ca8627d0a3e7a3563d41caa
Core tap last commit: 69 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 12.0 build 1200
Git: 2.31.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: 12.4
```

# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:

- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# Formula additions or changes

To get formulae added or changed in Brewsci/bio please file a [Pull Request](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md).

**Comment by sjackman** [comment]
This issue has been resolved.

**Comment by heuermh** [comment]
Thank you, can confirm it works for me now
