### ISSUE TITLE
Error in test suite - no cask with the name alsa-lib?

### ISSUE THREAD

**Issue by dzerbino** [brewsci/homebrew-bio#1324]
- What you were trying to do (and why)

Running CI tests for PR #1323 

- What happened (include command output)

Full output [here](https://github.com/brewsci/homebrew-bio/pull/1323/checks?check_run_id=2194392184)

Extract below:
```
==> brew uninstall --force alsa-lib apr apr-util autoconf automake berkeley-db binutils cmake cups docbook docbook-xsl flex fontconfig freeglut freetype gdbm ghostscript glib gpatch gperf groff help2man jasper jpeg json-c libdrm libedit libelf libffi libgcrypt libgpg-error libice libidn libpciaccess libpng libpthread-stubs libsm libtiff libtool libva libvdpau libx11 libxau libxcb libxdamage libxdmcp libxext libxfixes libxi libxinerama libxrandr libxrender libxshmfence libxslt libxt libxtst libxv libxvmc libxxf86vm libyaml llvm lm-sensors lz4 mawk mesa mesa-glu meson mpdecimal netpbm ninja openjdk pcre perl pkg-config psutils python@3.9 ruby scons sphinx-doc sqlite subversion swig tcl-tk texinfo uchardet unixodbc unzip utf8proc util-macros wayland wayland-protocols xcb-proto xinput xorgproto xtrans zip
==> FAILED
Error: No available formula or cask with the name "alsa-lib".
```

- What you expected to happen
   
CI tests to succeed as in the [MacOS test](https://github.com/brewsci/homebrew-bio/pull/1323/checks?check_run_id=2194392263)
    
- Step-by-step reproduction instructions (by running `brew install` commands)

See #1323

**Comment by dzerbino** [comment]
Hmm, evidently the issue got sorted, closing ticket.

**Comment by sjackman** [comment]
It appears to have been a transient error. I re-ran the test suite, and it passed.

**Comment by sjackman** [comment]
Or perhaps more likely it was an upstream Linuxbrew-core issue that was fixed upstream.
