### ISSUE TITLE
Software compilation failed

### ISSUE THREAD

**Issue by C2051** [brewsci/homebrew-bio#1345]
I came across an issue when I install the genewise，the following is the error code：
compilation terminated.
makefile:179: recipe for target 'subseqhash.o' failed
make[1]: *** [subseqhash.o] Error 1
make[1]: Leaving directory '/home/wangdan/anaconda3/bin/wise2.4.1/src/dynlibsrc'
makefile:87: recipe for target 'realall' failed

I would very thank you if you could solve this issue.

**Comment by sjackman** [comment]
Your error appears to be related to Anaconda, which is a different package manager than Homebrew.
Try `brew install brewsci/bio/genewise`
