### ISSUE TITLE
All CI linux builds fail: "Initializing the repository /usr/bin/git init Permission denied"

### ISSUE THREAD

**Issue by corneliusroemer** [brewsci/homebrew-bio#1395]
All PRs (at least the first two I checked) seem to have linux builds fail in Github actions with the following stack trace:
```
Initializing the repository
  /usr/bin/git init /__w/homebrew-bio/homebrew-bio
  /__w/homebrew-bio/homebrew-bio/.git: Permission denied
  Error: The process '/usr/bin/git' failed with exit code 1
```

See here for details: https://github.com/brewsci/homebrew-bio/pull/1394/checks?check_run_id=3335797430

![image](https://user-images.githubusercontent.com/25161793/129601810-11102c46-2664-4c3d-8476-ac48e7e9192a.png)

**Comment by corneliusroemer** [comment]
Can someone restart the GitHub actions? They should work now but don't run on their own without being triggered.

**Comment by YoshitakaMo** [comment]
I noticed that https://github.com/brewsci/homebrew-bio/actions/runs/1173580685 successfully passed the CI, but there seems an issue when merging the PR into the develop branch, https://github.com/brewsci/homebrew-bio/actions/runs/1184450246. Does anyone know the cause of this?

This is related to #1400.

**Comment by eseiler** [comment]
I think the easiest would be to rebase any of the open PRs onto the current develop; and merge it if the CI (`build bottle`) runs through. 
The failure on the develop branch (`upload bottle`) seems like it's caused by commits being pushed that do not change any formulas.

**Comment by YoshitakaMo** [comment]
Thank you for your suggestion! Both `build bottle` & `upload bottle` steps worked. (https://github.com/brewsci/homebrew-bio/pull/1406)
The currently open PRs will also work if you merge the latest commit and do PR again.

**Comment by sjackman** [comment]
Thank you very much for your work on fixing this issue, @YoshitakaMo @eseiler @corneliusroemer! 🏆✨🥇
I'm pleased to see that this tap has enough community support that it can weather my summer absence. 😀
