### ISSUE TITLE
No supported vectorization found for your machine

### ISSUE THREAD

**Issue by irinatu** [brewsci/homebrew-bio#1456]
# Please fill out the issue checklist below, and provide all of the requested information.
I wanted to install Infernal on ma mac. During the ./configure command on the macOS M1, I have an error:
...
configure: ::::::::::--- no vector instruction set ---::::::::::
configure: Infernal requires SSE or VMX vector instructions.
configure: Supported platforms are x86 (Intel/AMD) and PowerPC.
configure: error: No supported vectorization found for your machine.

The same situation after using brew

**Comment by sjackman** [comment]
http://eddylab.org/infernal/
Best to contact the author of Infernal.
