### ISSUE TITLE
Error installing roary

### ISSUE THREAD

**Issue by pgcudahy** [brewsci/homebrew-bio#1512]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:

- [X] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new.
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)
Install roary
- What happened (include command output)
```
==> Downloading https://ghcr.io/v2/brewsci/bio/roary/manifests/3.13.0_2
curl: (22) The requested URL returned error: 404                              

Error: roary: Failed to download resource "roary_bottle_manifest"
Download failed: https://ghcr.io/v2/brewsci/bio/roary/manifests/3.13.0_2
```
- What you expected to happen
Install roary
- Step-by-step reproduction instructions (by running `brew install` commands)
`brew install brewsci/bio/roary`
# Formula additions or changes

To get formulae added or changed in Brewsci/bio please file a [Pull Request](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md).

**Comment by YoshitakaMo** [comment]
Recently I've updated roary to work. You can install roary with `brew install brewsci/bio/roary`, but not tested well. Your feedback would be greatly appreciated.
