### ISSUE TITLE
Installation error of apbspdb2pqr

### ISSUE THREAD

**Issue by jongseo-park** [brewsci/homebrew-bio#1517]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:

- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)

`brew install brewsci/bio/apbspdb2pqr`

- What happened (include command output)

```
==> Cloning https://github.com/Electrostatics/apbs-pdb2pqr.git
Updating /Users/jongseo/Library/Caches/Homebrew/apbspdb2pqr--git
==> Checking out tag vAPBS-1.5.0
HEAD is now at aa353941 adding juans changes to rexpcalc
HEAD is now at aa353941 adding juans changes to rexpcalc
Entering 'apbs/externals/bem'
Entering 'apbs/externals/fetk'
Entering 'apbs/externals/geoflow_c'
Entering 'apbs/externals/mesh_routines'
Entering 'apbs/externals/pb_s_am'
/Users/jongseo/Library/Caches/Homebrew/apbspdb2pqr--git/apbs/externals/bem
/Users/jongseo/Library/Caches/Homebrew/apbspdb2pqr--git/apbs/externals/fetk
/Users/jongseo/Library/Caches/Homebrew/apbspdb2pqr--git/apbs/externals/geoflow_c
/Users/jongseo/Library/Caches/Homebrew/apbspdb2pqr--git/apbs/externals/mesh_routines
/Users/jongseo/Library/Caches/Homebrew/apbspdb2pqr--git/apbs/externals/pb_s_am
==> Installing apbspdb2pqr from brewsci/bio
==> cmake .. -DCMAKE_POLICY_DEFAULT_CMP0046=OLD -DCMAKE_POLICY_DEFAULT_CMP0078=O
==> make install
==> python scons/scons.py PREFIX=/opt/homebrew/Cellar/apbspdb2pqr/1.5.0/pdb2pqr 
Last 15 lines from /Users/jongseo/Library/Logs/Homebrew/apbspdb2pqr/03.python:
2022-03-19 15:07:21 +0000

python
scons/scons.py
PREFIX=/opt/homebrew/Cellar/apbspdb2pqr/1.5.0/pdb2pqr
APBS=/opt/homebrew/Cellar/apbspdb2pqr/1.5.0/bin/apbs
BUILD_PDB2PKA=False


If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/brewsci/homebrew-bio/issues

These open issues may also help:
apbspdb2pqr 3.0.0 https://github.com/brewsci/homebrew-bio/pull/1481
```

- What you expected to happen
Successful installation of the abps & pdb2pqr

- Step-by-step reproduction instructions (by running `brew install` commands)
`brew install brewsci/bio/apbspdb2pqr`

<br>
<br>

Recently, I have updated the macOS version to 12.3.

And I think that this error was occurred due to the deprecation of python2 in macOS 12.3.

When I checked the file in  `~/Library/Logs/Homebrew/apbspdb2pqr/03.python`,

there is a path list as below

```
PATH: /opt/homebrew/Library/Homebrew/shims/mac/super:
/opt/homebrew/opt/cmake/bin:/opt/homebrew/opt/icu4c/bin:
/opt/homebrew/opt/gdbm/bin:/opt/homebrew/opt/openssl@1.1/bin:
/opt/homebrew/opt/sqlite/bin:/opt/homebrew/opt/xz/bin:
/opt/homebrew/opt/python@3.9/bin:/opt/homebrew/opt/pcre/bin:
/opt/homebrew/opt/swig/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

Since the python2 is deprecated in the macOS 12.3, I installed pyenv and create a environment with python2.7.18, and created a symbolic link of `.../.pyenv/versions/2.7.18/bin/python2.7` to `/opt/homebrew/bin/python`.

And the symbolic link `/opt/homebrew/bin/python` was not on the path list.

So, I re-created the symbolic link to `/opt/homebrew/opt/python@3.9/bin/python` that is on the path list.

Finally, the installation was success using `brew install brewsci/bio/apbspdb2pqr`.

Unfortunately, I don't know the Ruby, so I couldn't modify the apbspdb2pqr.rb file.

I hope it will be updated soon.

**Comment by YoshitakaMo** [comment]
I created `apbspdb2pqr.rb` a long time ago, but for now, I recommend you install it without Homebrew because the installation from source on macOS (both Intel Mac and M1) requires some tricks. See also https://github.com/Electrostatics/FETK/issues/62 and [my formula](https://gist.github.com/YoshitakaMo/8cc5389ef55d820f688d4c6b1200ab9c). I recommend their official binaries instead.

But it is possible to create a patch and release a new Formula without waiting for the developer to fix it. I'll try to update when I have time.

**Comment by YoshitakaMo** [comment]
@jongseo-park I renewed apbs 3.4.0 https://github.com/brewsci/homebrew-bio/pull/1541 . Now that apbs and pdb2pqr packages are independently developed, the formulae should be divided.

```bash
$ brew uninstall apbs2pdb2pqr
$ brew install brewsci/bio/apbs
```

pdb2pqr is currently recommended to be installed with pip.
