### ISSUE TITLE
Can't install pymol

### ISSUE THREAD

**Issue by PortlandNMR** [brewsci/homebrew-bio#1566]
I've installed PyMOL successfully in the past on macOS computers, but in the last couple of weeks I've been unable to install it on a new M1 iMac that I'm setting up (macOS 12.5).

# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:

- [X] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new.

This is only a problem for installing PyMOL.

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

I just get "Error: Not Found"

- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

brew config output:

HOMEBREW_VERSION: 3.5.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3748bed378401ed75abdf32bcb3d2674d854a6f9
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9c9cfcdc31f2db06652c6e456cefecdc1427ebf7
Core tap last commit: 30 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.U0VpI5x3hM/org.xquartz:0
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.32.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.5-arm64
CLT: 13.4.0.0.1.1651278267
Xcode: N/A
Rosetta 2: false

brew doctor output:

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libcpsrt.dylib

To help us debug your issue please explain:

- What you were trying to do (and why)

Trying to install PyMOL (brew install pymol)

- What happened (include command output)

Output below:

==> Downloading https://files.pythonhosted.org/packages/61/3c/2206f39880d38ca7ad8ac1b28d2d5ca81632d163b2d68ef90e46409ca057/msgpack-1.0.3.tar.gz
Already downloaded: /Users/loening/Library/Caches/Homebrew/downloads/8bee0f0b5208ddbcdd7e9ed2ea1f0e8711506335ca8d8143fb4b0e0208272d73--msgpack-1.0.3.tar.gz
==> Downloading https://files.pythonhosted.org/packages/13/ea/c6a302ccdfdcc1ab200bd2b7561e574329055d2974b1fb7939a7aa374da3/mmtf-python-1.1.2.tar.gz
Already downloaded: /Users/loening/Library/Caches/Homebrew/downloads/8184cd2975ddc6f5276f8aca6273b4b0e2e98a69ae60a94e8f087e2bf4f7fbc2--mmtf-python-1.1.2.tar.gz
==> Downloading https://altushost-swe.dl.sourceforge.net/project/pmw/Pmw-2.1.tar.gz
Already downloaded: /Users/loening/Library/Caches/Homebrew/downloads/15507022da5f57d4a0e48ea2eee93a2e42945009c083a6a0e69f9a77aedd67d5--Pmw-2.1.tar.gz
==> Downloading https://github.com/schrodinger/pymol-open-source/archive/v2.5.0.tar.gz
Already downloaded: /Users/loening/Library/Caches/Homebrew/downloads/026e19fbe9447262d569f99bdc16c32df38d2654c09f047ff9e84be5a4655e73--pymol-open-source-2.5.0.tar.gz
==> Installing pymol from brewsci/bio
==> /opt/homebrew/opt/python@3.9/bin/python3 -c import setuptools... --no-user-cfg install --prefix=/opt/homebrew/Cellar/pymol/2.5.0_3/libexec --install-scripts=/opt/homebrew/Cellar/pymol/2.5.0_3/libexec/
Last 15 lines from /Users/loening/Library/Logs/Homebrew/pymol/01.python3:

/opt/homebrew/opt/python@3.9/bin/python3
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/opt/homebrew/Cellar/pymol/2.5.0_3/libexec
--install-scripts=/opt/homebrew/Cellar/pymol/2.5.0_3/libexec/bin
--install-lib=/opt/homebrew/Cellar/pymol/2.5.0_3/libexec/lib/python3.10/site-packages
--single-version-externally-managed
--record=installed.txt

Do not report this issue to Homebrew/brew or Homebrew/core!

- What you expected to happen

I expected PyMOL to install as it has in the past.

- Step-by-step reproduction instructions (by running `brew install` commands)

    brew install pymol
and
     brew install brewsci/bio/pymol 
lead to the same error.

# Formula additions or changes

To get formulae added or changed in Brewsci/bio please file a [Pull Request](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md).

**Comment by brendanmilroy** [comment]
Also having the same issue

**Comment by ww2283** [comment]
similar issue here. I have successfully installed pymol 2.5.0, but cannot use homebrew to update it to current version 2.5.0_3. M1 MacBook pro 2021 14inch.

**Comment by YoshitakaMo** [comment]
Hi, I'm the maintainer of Homebrew PyMOL. I've also encountered this issue on not only a M1 mac but also Intel Mac when trying `--build-from-source`. I guess the cause is probably a new dependency on `python@3.10`. I'll try to figure out how to fix it.

**Comment by YoshitakaMo** [comment]
Now I've fixed this issue. Please try the installation again!

**Comment by PortlandNMR** [comment]
That worked for me...thanks! Having PyMOL available through Homebrew is incredibly useful for me, and I very much appreciate your work on this.
