### ISSUE TITLE
brewsci/bio/emboss fails brew audit, Dependency 'postgresql' was renamed

### ISSUE THREAD

**Issue by heuermh** [brewsci/homebrew-bio#1572]
```
==> brew audit --tap=brewsci/bio
==> FAILED
Full audit --tap=brewsci/bio output
  Warning: Use postgresql@14 instead of deprecated postgresql
  brewsci/bio/emboss:
    * Dependency 'postgresql' was renamed; use new name 'postgresql@14'.
  Error: 1 problem in 1 formula detected
  Error: Dependency 'postgresql' was renamed; use new name 'postgresql@14'.
Error: 1 failed step!
```
https://github.com/brewsci/homebrew-bio/runs/8256417608?check_suite_focus=true

**Comment by jonchang** [comment]
Can you open a pull request for this? Thanks! The formula will also need a revision bump.

**Comment by heuermh** [comment]
Thanks, @jonchang, beat me to it!  😁

**Comment by heuermh** [comment]
Hold up, this still appears to be an issue for me.  I rerun the failed jobs on #1571 and they are still failing.

**Comment by czhu** [comment]
same issue here.

**Comment by jonchang** [comment]
https://github.com/brewsci/homebrew-bio/issues/1572#issuecomment-1241105807
