### ISSUE TITLE
install brewsci/bio/bowtie bug: /usr/local/bin/bowtie: bad interpreter: /usr/local/opt/python@3.9/bin/python3

### ISSUE THREAD

**Issue by jamesbraza** [brewsci/homebrew-bio#1584]
# Please always follow these steps:

- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```bash
> brew gist-logs brewsci/bio/bowtie
Error: No logs.
> brew config
HOMEBREW_VERSION: 3.6.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 99682c5af3b48e7b37bf9c565781800153ee88fb
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1b5198f9f1e6771fd908a6aa0d108ac9cc2728fa
Core tap last commit: 28 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 13.0.0 build 1300
Git: 2.37.3 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.5.1-x86_64
CLT: 13.2.0.0.1.1638488800
Xcode: N/A
```

To help us debug your issue please explain:

- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

I tapped this repo and went to install [`bowtie`](https://bowtie-bio.sourceforge.net/index.shtml):

```bash
> brew tap brewsci/bio
> brew install brewsci/bio/bowtie
> bowtie
zsh: /usr/local/bin/bowtie: bad interpreter: /usr/local/opt/python@3.9/bin/python3: no such file or directory
> ls /usr/local/opt/python@3.9/bin/
2to3-3.9         idle3.9          pip3.9           pydoc3.9         python3.9        python3.9-config wheel3.9
```

It looks like the `bowtie` install hinges on a `python3` being at `/usr/local/opt/python@3.9/bin`, but it's not.

Running `ln -s /usr/local/opt/python@3.9/bin/python3.9 /usr/local/opt/python@3.9/bin/python3` fixes the issue.

# Formula additions or changes

To get formulae added or changed in Brewsci/bio please file a [Pull Request](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md).

**Comment by YoshitakaMo** [comment]
bowtie was migrated to Homebrew/core. This issue may have been fixed.
