### ISSUE TITLE
I have such a problem   Error: brewsci/bio/express 1.5.3 did not build

### ISSUE THREAD

**Issue by szpssss** [brewsci/homebrew-bio#1602]
I want to install trinity for analyzing the rna-seq.  when I install, input command such as  brew install -v trinity .  Installing brewsci/bio/trinity dependency: brewsci/bio/express
/usr/bin/env tar --extract --no-same-owner --file /Users/shengzepeng/Library/Caches/Homebrew/downloads/ccd1d4a736d88107deed63e9e694ed895d500e225f7b997d3cac2628158ce485--eXpress-1.5.3.tar.gz --directory /private/tmp/d20230309-12930-zjzgs3
/usr/bin/env cp -pR /private/tmp/d20230309-12930-zjzgs3/eXpress-1.5.3/. /private/tmp/express-20230309-12930-nx47i0/eXpress-1.5.3
==> cmake . -DCMAKE_INSTALL_PREFIX=/opt/homebrew/Cellar/express/1.5.3 -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DBUILD_TESTING=OFF -DCMAKE_OSX_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk
-- The C compiler identification is AppleClang 14.0.0.14000029
-- The CXX compiler identification is AppleClang 14.0.0.14000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/homebrew/Library/Homebrew/shims/mac/super/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/homebrew/Library/Homebrew/shims/mac/super/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Boost: /opt/homebrew/lib/cmake/Boost-1.81.0/BoostConfig.cmake (found suitable version "1.81.0", minimum required is "1.39") found components: thread system filesystem program_options date_time 
-- Found GPERFTOOLS_TCMALLOC: /opt/homebrew/lib/libtcmalloc.dylib
-- Found Protobuf: /opt/homebrew/lib/libprotobuf.dylib (found version "3.21.12") 
-- Found ZLIB: /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/lib/libz.tbd (found version "1.2.11") 
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    BUILD_TESTING
    CMAKE_INSTALL_LIBDIR

-- Build files have been written to: /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3
==> make install
/opt/homebrew/Cellar/cmake/3.25.3/bin/cmake -S/tmp/express-20230309-12930-nx47i0/eXpress-1.5.3 -B/tmp/express-20230309-12930-nx47i0/eXpress-1.5.3 --check-build-system CMakeFiles/Makefile.cmake 0
/opt/homebrew/Cellar/cmake/3.25.3/bin/cmake -E cmake_progress_start /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/CMakeFiles /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3//CMakeFiles/progress.marks
/Library/Developer/CommandLineTools/usr/bin/make  -f CMakeFiles/Makefile2 all
/Library/Developer/CommandLineTools/usr/bin/make  -f src/CMakeFiles/express.dir/build.make src/CMakeFiles/express.dir/depend
[ 11%] Running cpp protocol buffer compiler on /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/src/targets.proto
[ 11%] Running cpp protocol buffer compiler on /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/src/alignments.proto
cd /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/src && /opt/homebrew/bin/protoc --cpp_out /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/src -I /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/src /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/src/alignments.proto
cd /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/src && /opt/homebrew/bin/protoc --cpp_out /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/src -I /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/src /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/src/targets.proto
[libprotobuf WARNING /tmp/protobuf-20230204-6305-1lmm44q/protobuf-21.12/src/google/protobuf/compiler/parser.cc:646] No syntax specified for the proto file: targets.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
[libprotobuf WARNING /tmp/protobuf-20230204-6305-1lmm44q/protobuf-21.12/src/google/protobuf/compiler/parser.cc:646] No syntax specified for the proto file: alignments.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
cd /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3 && /opt/homebrew/Cellar/cmake/3.25.3/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3 /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/src /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3 /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/src /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/src/CMakeFiles/express.dir/DependInfo.cmake --color=
/Library/Developer/CommandLineTools/usr/bin/make  -f src/CMakeFiles/express.dir/build.make src/CMakeFiles/express.dir/build
[ 22%] Building CXX object src/CMakeFiles/express.dir/main.cpp.o
[ 22%] Building CXX object src/CMakeFiles/express.dir/biascorrection.cpp.o
cd /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/src && /opt/homebrew/Library/Homebrew/shims/mac/super/clang++ -DBOOST_ATOMIC_NO_LIB -DBOOST_DATE_TIME_NO_LIB -DBOOST_FILESYSTEM_NO_LIB -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_SYSTEM_NO_LIB -DBOOST_THREAD_NO_LIB -I/tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/bamtools/include -Wall -O3 -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -std=gnu++11 -MD -MT src/CMakeFiles/express.dir/main.cpp.o -MF CMakeFiles/express.dir/main.cpp.o.d -o CMakeFiles/express.dir/main.cpp.o -c /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/src/main.cpp
cd /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/src && /opt/homebrew/Library/Homebrew/shims/mac/super/clang++ -DBOOST_ATOMIC_NO_LIB -DBOOST_DATE_TIME_NO_LIB -DBOOST_FILESYSTEM_NO_LIB -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_SYSTEM_NO_LIB -DBOOST_THREAD_NO_LIB -I/tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/bamtools/include -Wall -O3 -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -std=gnu++11 -MD -MT src/CMakeFiles/express.dir/biascorrection.cpp.o -MF CMakeFiles/express.dir/biascorrection.cpp.o.d -o CMakeFiles/express.dir/biascorrection.cpp.o -c /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/src/biascorrection.cpp
[ 27%] Building CXX object src/CMakeFiles/express.dir/bundles.cpp.o
[ 33%] Building CXX object src/CMakeFiles/express.dir/directiondetector.cpp.o
cd /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/src && /opt/homebrew/Library/Homebrew/shims/mac/super/clang++ -DBOOST_ATOMIC_NO_LIB -DBOOST_DATE_TIME_NO_LIB -DBOOST_FILESYSTEM_NO_LIB -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_SYSTEM_NO_LIB -DBOOST_THREAD_NO_LIB -I/tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/bamtools/include -Wall -O3 -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -std=gnu++11 -MD -MT src/CMakeFiles/express.dir/bundles.cpp.o -MF CMakeFiles/express.dir/bundles.cpp.o.d -o CMakeFiles/express.dir/bundles.cpp.o -c /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/src/bundles.cpp
[ 38%] Building CXX object src/CMakeFiles/express.dir/mapparser.cpp.o
cd /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/src && /opt/homebrew/Library/Homebrew/shims/mac/super/clang++ -DBOOST_ATOMIC_NO_LIB -DBOOST_DATE_TIME_NO_LIB -DBOOST_FILESYSTEM_NO_LIB -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_SYSTEM_NO_LIB -DBOOST_THREAD_NO_LIB -I/tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/bamtools/include -Wall -O3 -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -std=gnu++11 -MD -MT src/CMakeFiles/express.dir/mapparser.cpp.o -MF CMakeFiles/express.dir/mapparser.cpp.o.d -o CMakeFiles/express.dir/mapparser.cpp.o -c /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/src/mapparser.cpp
[ 44%] Building CXX object src/CMakeFiles/express.dir/lengthdistribution.cpp.o
cd /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/src && /opt/homebrew/Library/Homebrew/shims/mac/super/clang++ -DBOOST_ATOMIC_NO_LIB -DBOOST_DATE_TIME_NO_LIB -DBOOST_FILESYSTEM_NO_LIB -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_SYSTEM_NO_LIB -DBOOST_THREAD_NO_LIB -I/tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/bamtools/include -Wall -O3 -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -std=gnu++11 -MD -MT src/CMakeFiles/express.dir/directiondetector.cpp.o -MF CMakeFiles/express.dir/directiondetector.cpp.o.d -o CMakeFiles/express.dir/directiondetector.cpp.o -c /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/src/directiondetector.cpp
[ 50%] Building CXX object src/CMakeFiles/express.dir/markovmodel.cpp.o
cd /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/src && /opt/homebrew/Library/Homebrew/shims/mac/super/clang++ -DBOOST_ATOMIC_NO_LIB -DBOOST_DATE_TIME_NO_LIB -DBOOST_FILESYSTEM_NO_LIB -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_SYSTEM_NO_LIB -DBOOST_THREAD_NO_LIB -I/tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/bamtools/include -Wall -O3 -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -std=gnu++11 -MD -MT src/CMakeFiles/express.dir/lengthdistribution.cpp.o -MF CMakeFiles/express.dir/lengthdistribution.cpp.o.d -o CMakeFiles/express.dir/lengthdistribution.cpp.o -c /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/src/lengthdistribution.cpp
[ 55%] Building CXX object src/CMakeFiles/express.dir/fragments.cpp.o
cd /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/src && /opt/homebrew/Library/Homebrew/shims/mac/super/clang++ -DBOOST_ATOMIC_NO_LIB -DBOOST_DATE_TIME_NO_LIB -DBOOST_FILESYSTEM_NO_LIB -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_SYSTEM_NO_LIB -DBOOST_THREAD_NO_LIB -I/tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/bamtools/include -Wall -O3 -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -std=gnu++11 -MD -MT src/CMakeFiles/express.dir/fragments.cpp.o -MF CMakeFiles/express.dir/fragments.cpp.o.d -o CMakeFiles/express.dir/fragments.cpp.o -c /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/src/fragments.cpp
cd /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/src && /opt/homebrew/Library/Homebrew/shims/mac/super/clang++ -DBOOST_ATOMIC_NO_LIB -DBOOST_DATE_TIME_NO_LIB -DBOOST_FILESYSTEM_NO_LIB -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_SYSTEM_NO_LIB -DBOOST_THREAD_NO_LIB -I/tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/bamtools/include -Wall -O3 -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -std=gnu++11 -MD -MT src/CMakeFiles/express.dir/markovmodel.cpp.o -MF CMakeFiles/express.dir/markovmodel.cpp.o.d -o CMakeFiles/express.dir/markovmodel.cpp.o -c /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/src/markovmodel.cpp
[ 61%] Building CXX object src/CMakeFiles/express.dir/mismatchmodel.cpp.o
cd /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/src && /opt/homebrew/Library/Homebrew/shims/mac/super/clang++ -DBOOST_ATOMIC_NO_LIB -DBOOST_DATE_TIME_NO_LIB -DBOOST_FILESYSTEM_NO_LIB -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_SYSTEM_NO_LIB -DBOOST_THREAD_NO_LIB -I/tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/bamtools/include -Wall -O3 -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -std=gnu++11 -MD -MT src/CMakeFiles/express.dir/mismatchmodel.cpp.o -MF CMakeFiles/express.dir/mismatchmodel.cpp.o.d -o CMakeFiles/express.dir/mismatchmodel.cpp.o -c /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/src/mismatchmodel.cpp
[ 66%] Building CXX object src/CMakeFiles/express.dir/robertsfilter.cpp.o
cd /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/src && /opt/homebrew/Library/Homebrew/shims/mac/super/clang++ -DBOOST_ATOMIC_NO_LIB -DBOOST_DATE_TIME_NO_LIB -DBOOST_FILESYSTEM_NO_LIB -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_SYSTEM_NO_LIB -DBOOST_THREAD_NO_LIB -I/tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/bamtools/include -Wall -O3 -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -std=gnu++11 -MD -MT src/CMakeFiles/express.dir/robertsfilter.cpp.o -MF CMakeFiles/express.dir/robertsfilter.cpp.o.d -o CMakeFiles/express.dir/robertsfilter.cpp.o -c /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/src/robertsfilter.cpp
[ 72%] Building CXX object src/CMakeFiles/express.dir/sequence.cpp.o
cd /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/src && /opt/homebrew/Library/Homebrew/shims/mac/super/clang++ -DBOOST_ATOMIC_NO_LIB -DBOOST_DATE_TIME_NO_LIB -DBOOST_FILESYSTEM_NO_LIB -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_SYSTEM_NO_LIB -DBOOST_THREAD_NO_LIB -I/tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/bamtools/include -Wall -O3 -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -std=gnu++11 -MD -MT src/CMakeFiles/express.dir/sequence.cpp.o -MF CMakeFiles/express.dir/sequence.cpp.o.d -o CMakeFiles/express.dir/sequence.cpp.o -c /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/src/sequence.cpp
[ 77%] Building CXX object src/CMakeFiles/express.dir/targets.cpp.o
cd /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/src && /opt/homebrew/Library/Homebrew/shims/mac/super/clang++ -DBOOST_ATOMIC_NO_LIB -DBOOST_DATE_TIME_NO_LIB -DBOOST_FILESYSTEM_NO_LIB -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_SYSTEM_NO_LIB -DBOOST_THREAD_NO_LIB -I/tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/bamtools/include -Wall -O3 -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -std=gnu++11 -MD -MT src/CMakeFiles/express.dir/targets.cpp.o -MF CMakeFiles/express.dir/targets.cpp.o.d -o CMakeFiles/express.dir/targets.cpp.o -c /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/src/targets.cpp
[ 83%] Building CXX object src/CMakeFiles/express.dir/threadsafety.cpp.o
cd /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/src && /opt/homebrew/Library/Homebrew/shims/mac/super/clang++ -DBOOST_ATOMIC_NO_LIB -DBOOST_DATE_TIME_NO_LIB -DBOOST_FILESYSTEM_NO_LIB -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_SYSTEM_NO_LIB -DBOOST_THREAD_NO_LIB -I/tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/bamtools/include -Wall -O3 -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -std=gnu++11 -MD -MT src/CMakeFiles/express.dir/threadsafety.cpp.o -MF CMakeFiles/express.dir/threadsafety.cpp.o.d -o CMakeFiles/express.dir/threadsafety.cpp.o -c /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/src/threadsafety.cpp
[ 88%] Building CXX object src/CMakeFiles/express.dir/alignments.pb.cc.o
cd /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/src && /opt/homebrew/Library/Homebrew/shims/mac/super/clang++ -DBOOST_ATOMIC_NO_LIB -DBOOST_DATE_TIME_NO_LIB -DBOOST_FILESYSTEM_NO_LIB -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_SYSTEM_NO_LIB -DBOOST_THREAD_NO_LIB -I/tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/bamtools/include -Wall -O3 -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -std=gnu++11 -MD -MT src/CMakeFiles/express.dir/alignments.pb.cc.o -MF CMakeFiles/express.dir/alignments.pb.cc.o.d -o CMakeFiles/express.dir/alignments.pb.cc.o -c /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/src/alignments.pb.cc
make[2]: *** No rule to make target `/opt/homebrew/lib/libprotobuf.a', needed by `src/express'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 94%] Building CXX object src/CMakeFiles/express.dir/targets.pb.cc.o
cd /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/src && /opt/homebrew/Library/Homebrew/shims/mac/super/clang++ -DBOOST_ATOMIC_NO_LIB -DBOOST_DATE_TIME_NO_LIB -DBOOST_FILESYSTEM_NO_LIB -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_SYSTEM_NO_LIB -DBOOST_THREAD_NO_LIB -I/tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/bamtools/include -Wall -O3 -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -std=gnu++11 -MD -MT src/CMakeFiles/express.dir/targets.pb.cc.o -MF CMakeFiles/express.dir/targets.pb.cc.o.d -o CMakeFiles/express.dir/targets.pb.cc.o -c /tmp/express-20230309-12930-nx47i0/eXpress-1.5.3/src/targets.pb.cc
make[1]: *** [src/CMakeFiles/express.dir/all] Error 2
make: *** [all] Error 2

==> Formula
Tap: brewsci/bio
Path: /opt/homebrew/Library/Taps/brewsci/homebrew-bio/Formula/express.rb
==> Configuration
HOMEBREW_VERSION: 4.0.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: b1ef41c25d12795dc93975e337e8644d0974b53c
Last commit: 3 days ago
Core tap JSON: 09 Mar 01:47 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2.1-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
Rosetta 2: false
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /opt/homebrew
CMAKE_INCLUDE_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_PATH: /opt/homebrew/opt/bamtools/lib/pkgconfig:/opt/homebrew/opt/gperftools/lib/pkgconfig:/opt/homebrew/opt/protobuf/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/opt/homebrew/Library/Homebrew/os/mac/pkgconfig/13
HOMEBREW_GIT: git
HOMEBREW_SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk
ACLOCAL_PATH: /opt/homebrew/share/aclocal
PATH: /opt/homebrew/Library/Homebrew/shims/mac/super:/opt/homebrew/opt/bamtools/bin:/opt/homebrew/opt/cmake/bin:/opt/homebrew/opt/gperftools/bin:/opt/homebrew/opt/protobuf/bin:/usr/bin:/bin:/usr/sbin:/sbin

Error: brewsci/bio/express 1.5.3 did not build
Logs:
     /Users/shengzepeng/Library/Logs/Homebrew/express/00.options.out
     /Users/shengzepeng/Library/Logs/Homebrew/express/CMakeFiles
     /Users/shengzepeng/Library/Logs/Homebrew/express/01.cmake.cc
     /Users/shengzepeng/Library/Logs/Homebrew/express/01.cmake
     /Users/shengzepeng/Library/Logs/Homebrew/express/02.make.cc
     /Users/shengzepeng/Library/Logs/Homebrew/express/CMakeCache.txt
     /Users/shengzepeng/Library/Logs/Homebrew/express/02.make
If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/brewsci/homebrew-bio/issues

**Comment by YoshitakaMo** [comment]
This issue has been fixed now.
