### ISSUE TITLE
Error when intalling Prokka using Brew

### ISSUE THREAD

**Issue by VJZV** [brewsci/homebrew-bio#1610]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:

- [ ] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new.
- [ ] Ran `brew update` and retried your prior step?
- [ ] Already up-to-date.
- [ ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  brew-pip

- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] No available formula with the name "tb12asn--doc".
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)
- Trying to install Prokka using $ brew install brewsci/bio/prokka
- What happened (include command output)
- Error: prokka: Failed to download resource "tb12asn--doc"
Download failed: https://ftp.ncbi.nih.gov/toolbox/ncbi_tools/converters/by_progr
am/tb12asn/DOCUMENTATION/tb12asn. txt
- What you expected to happen
- Properly install Prokka
- Step-by-step reproduction instructions (by running `brew install` commands)
==> Fetching brewsci/bio/tb12asn
==> Downloading https://ftp.ncbi.nih.gov/toolbox/ncbi_tools/converters/by_progra
curl: (22) The requested URL returned error: 404
# Formula additions or changes

To get formulae added or changed in Brewsci/bio please file a [Pull Request](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md).

**Comment by YoshitakaMo** [comment]
Now this issue has been fixed. Please try `brew install brewsci/bio/prokka`.
