### ISSUE TITLE
iqtree2 on m1: "gcc-12: error: unrecognized command-line option '-msse3'"

### ISSUE THREAD

**Issue by holmrenser** [brewsci/homebrew-bio#1611]
I ran `brew install brewsci/bio/iqtree2` on my macbook pro m1 and got the following error:
```
Last 15 lines from /Users/rensholmer/Library/Logs/Homebrew/iqtree2/02.make:
make[1]: *** [pll/CMakeFiles/pll.dir/all] Error 2
make[2]: *** [ncl/CMakeFiles/ncl.dir/nxsblock.cpp.o] Error 1make[2]: *** [terraphast/CMakeFiles/terraphast.dir/lib/bigint.cpp.o] Error 1

make[1]: *** [ncl/CMakeFiles/ncl.dir/all] Error 2
make[2]: *** [booster/CMakeFiles/booster.dir/io.c.o] Error 1
g++-12: error: unrecognized command-line option '-msse3'
g++-12: error: unrecognized command-line option '-msse3'
make[2]: *** [gsl/CMakeFiles/gsl.dir/pow_int.cpp.o] Error 1
make[2]: *** [terraphast/CMakeFiles/terraphast.dir/lib/bipartitions.cpp.o] Error 1
make[1]: *** [gsl/CMakeFiles/gsl.dir/all] Error 2
make[1]: *** [terraphast/CMakeFiles/terraphast.dir/all] Error 2
gcc-12: error: unrecognized command-line option '-msse3'
make[2]: *** [booster/CMakeFiles/booster.dir/sort.c.o] Error 1
make[1]: *** [booster/CMakeFiles/booster.dir/all] Error 2
make: *** [all] Error 2
```

gist with logs: https://gist.github.com/holmrenser/95d9289e6d9c92cd0de179084be1b5ca

**Comment by holmrenser** [comment]
Related: https://github.com/iqtree/iqtree2/issues/126#issuecomment-1471009928

Apparently iqtree does not yet support m1/m2 hardware. Should it then be possible to 'install' with brew?

**Comment by corneliusroemer** [comment]
@holmrenser I got it to compile via brew with a patch or two on my M1, see: https://github.com/Homebrew/homebrew-core/blob/573b15f29e31ba4143ae8137111cf87a3f181829/Formula/iqtree2.rb

**Comment by jsan4christ** [comment]
Hi @corneliusroemer interesting, how would one implement this patch to run it on an M2? Thanks

**Comment by Gat2018** [comment]
I got same problem and failed to fix   
Installing iqtree2 from brewsci/bio
==> cmake ..
==> make install
Last 15 lines from /Users/gasparymwanyika/Library/Logs/Homebrew/iqtree2/02.make:
make[2]: *** [sprng/CMakeFiles/sprng.dir/memory.c.o] Error 1
make[1]: *** [sprng/CMakeFiles/sprng.dir/all] Error 2
g++-13: error: unrecognized command-line option '-msse3'
make[2]: *** [terraphast/CMakeFiles/terraphast.dir/lib/bipartitions.cpp.o] Error 1
g++-13: error: unrecognized command-line option '-msse3'
g++-13: error: unrecognized command-line option '-msse3'
g++-13: error: unrecognized command-line option '-msse3'
make[2]: *** [ncl/CMakeFiles/ncl.dir/nxscharactersblock.cpp.o] Error 1
make[2]: *** [ncl/CMakeFiles/ncl.dir/nxsdatablock.cpp.o] Error 1
make[2]: *** [terraphast/CMakeFiles/terraphast.dir/lib/bitmatrix.cpp.o] Error 1
make[1]: *** [terraphast/CMakeFiles/terraphast.dir/all] Error 2
g++-13: error: unrecognized command-line option '-msse3'
make[2]: *** [ncl/CMakeFiles/ncl.dir/nxsdiscretedatum.cpp.o] Error 1
make[1]: *** [ncl/CMakeFiles/ncl.dir/all] Error 2
make: *** [all] Error 2

Do not report this issue to Homebrew/brew or Homebrew/homebrew-core!

These open issues may also help:
iqtree2 on m1: "gcc-12: error: unrecognized command-line option '-msse3'" https://github.com/brewsci/homebrew-bio/issues/1611
gasparymwanyika@Bridgets-MacBook-Pro Downloads %

**Comment by corneliusroemer** [comment]
iqtree2 now supports arm - I don't know enough about homebrew to enable this in the recipe.

This works to build from source for me on my M1 arm mac:

```bash
gh repo clone iqtree/iqtree2
cd iqtree2
git submodule init
git submodule update
mkdir build
cd build
cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ ..
make -j
```

**Comment by YoshitakaMo** [comment]
I've updated iqtree2 v.2.3.3 now. Please use it instead.

```
brew update && brew install brewsci/bio/iqtree2
```
