### ISSUE TITLE
unzip SPAdes-3.15.5-Darwin.tar.gz

### ISSUE THREAD

**Issue by VaneFerPas** [brewsci/homebrew-bio#1617]
I'm working from the terminal of a Mac M1. I have downloaded the Spades binaries but when I unpack SPAdes-3.15.5-Darwin.tar.gz I get the following error: tar: Error opening archive: Unrecognized archive format. It won't let me move on. What could I do?

**Comment by YoshitakaMo** [comment]
Homebrew-SPAdes is not included in this repository, and it seems SPAdes doesn't support M1 Mac currently. https://github.com/ablab/spades/issues/1062
