### ISSUE TITLE
Invalid version specifier for star-aligner

### ISSUE THREAD

**Issue by heuermh** [brewsci/homebrew-bio#1638]
@jonchang @czhu

See e.g.
https://github.com/brewsci/homebrew-bio/actions/runs/5953969678/job/16721819867?pr=1636

The currently used version specifier fails the audit regex check `^[a-zA-Z0-9_][a-zA-Z0-9._-]{0,127}$`
2.7.10a+220818

The following are allowed
2.7.10a-220818
2.7.10a_220818
2.7.10a.220818
2.7.10a220818

**Comment by YoshitakaMo** [comment]
This issue has been fixed now.

**Comment by heuermh** [comment]
Thank you, @YoshitakaMo!
