### ISSUE TITLE
ModuleNotfoundError " readfq" 

### ISSUE THREAD

**Issue by Shaileshdesai76** [brewsci/homebrew-bio#1651]
i was running the kmergenie to estimate but end up with this error . 
i have installed through conda 
but error says ModuleNotfoundErrro.

**Comment by YoshitakaMo** [comment]
I've tried to build and compile `kmergenie` yesterday, but I found that the python scripts no longer work with python >= 3.8 (probably) because of multiprocessing issue. Now that python@3.7 has been removed from homebrew, we will no longer maintain it.
