### ISSUE TITLE
iqtree installation

### ISSUE THREAD

**Issue by VandaGAdamkova** [brewsci/homebrew-bio#1661]
Dear all,

I tried to install iqtree from homebrew and I get the following error message:

command:  brew install brewsci/bio/iqtree

==> Fetching brewsci/bio/iqtree
==> Downloading https://github.com/Cibiv/IQ-TREE/archive/refs/tags/v1.6.12.tar.g
Already downloaded: /Users/vandaadamkova/Library/Caches/Homebrew/downloads/5463ff3c35dcbb1befece836488739dd9e7eb9c2121d5fc22550fabf87cb0b67--IQ-TREE-1.6.12.tar.gz
==> Installing iqtree from brewsci/bio
==> cmake .. -DIQTREE_FLAGS=omp
==> make
Last 15 lines from /Users/vandaadamkova/Library/Logs/Homebrew/iqtree/02.make:
make[1]: *** [ncl/CMakeFiles/ncl.dir/all] Error 2
gcc-13: error: unrecognized command-line option '-msse3'
make[2]: *** [pll/CMakeFiles/pll.dir/bipartitionList.c.o] Error 1
gcc-13: error: unrecognized command-line option '-msse3'
make[2]: *** [pll/CMakeFiles/pll.dir/evaluateGenericSpecial.c.o] Error 1
make[1]: *** [pll/CMakeFiles/pll.dir/all] Error 2
[ 11%] Building CXX object gsl/CMakeFiles/gsl.dir/gausspdf.cpp.o
cd /tmp/iqtree-20240105-60006-9fup1/IQ-TREE-1.6.12/build/gsl && /opt/homebrew/Library/Homebrew/shims/mac/super/g++-13 -DIQ_TREE -D_USE_PTHREADS -I/tmp/iqtree-20240105-60006-9fup1/IQ-TREE-1.6.12 -I/tmp/iqtree-20240105-60006-9fup1/IQ-TREE-1.6.12/build -std=c++11 -fopenmp -pthread  -O3 -g -ffunction-sections -fdata-sections -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk   -mmacosx-version-min=10.7 -I/opt/homebrew/include/eigen3 -DUSE_EIGEN3 -MD -MT gsl/CMakeFiles/gsl.dir/gausspdf.cpp.o -MF CMakeFiles/gsl.dir/gausspdf.cpp.o.d -o CMakeFiles/gsl.dir/gausspdf.cpp.o -c /tmp/iqtree-20240105-60006-9fup1/IQ-TREE-1.6.12/gsl/gausspdf.cpp
[ 11%] Linking CXX static library libgsl.a
cd /tmp/iqtree-20240105-60006-9fup1/IQ-TREE-1.6.12/build/gsl && /opt/homebrew/Cellar/cmake/3.28.1/bin/cmake -P CMakeFiles/gsl.dir/cmake_clean_target.cmake
cd /tmp/iqtree-20240105-60006-9fup1/IQ-TREE-1.6.12/build/gsl && /opt/homebrew/Cellar/cmake/3.28.1/bin/cmake -E cmake_link_script CMakeFiles/gsl.dir/link.txt --verbose=1
/usr/bin/ar qc libgsl.a CMakeFiles/gsl.dir/binomial_tpe.cpp.o CMakeFiles/gsl.dir/multinomial.cpp.o CMakeFiles/gsl.dir/pow_int.cpp.o CMakeFiles/gsl.dir/gauss.cpp.o CMakeFiles/gsl.dir/gaussinv.cpp.o CMakeFiles/gsl.dir/gausspdf.cpp.o
/usr/bin/ranlib libgsl.a
[ 11%] Built target gsl
make: *** [all] Error 2

I checked that I have gcc-13, I checked that my homebrew is up to date as well as I updated my command line to X15.1

But I still cannot install the iqtree.

Thank you for the help

**Comment by harrisonestes** [comment]
I am having the same issue.

**Comment by YoshitakaMo** [comment]
I've updated iqtree2 v.2.3.3 now. Please use it instead.
