### ISSUE TITLE
Error on brew install brewsci/bio/staden-io-lib

### ISSUE THREAD

**Issue by nekoqdesu** [brewsci/homebrew-bio#1664]
Dear all,

I tried to install iqtree from homebrew and I get the following error message:

% brew install brewsci/bio/staden-io-lib
==> Fetching brewsci/bio/staden-io-lib
==> Downloading https://github.com/jkbonfield/io_lib/releases/download/io_lib-1-
Already downloaded: /Users/minodaayumi/Library/Caches/Homebrew/downloads/3c0118a140a3d7f227b457b51b24ff3c57dce85253d0eb7f1346eeb3aa6ed443--io_lib-1.14.13.tar.gz
==> Installing staden-io-lib from brewsci/bio
==> ./configure --disable-silent-rules
==> make install
Error: inreplace failed
/opt/homebrew/Cellar/staden-io-lib/1.14.13/share/staden-io-lib/tests/Makefile:
  expected replacement of "/opt/homebrew/Library/Homebrew/shims/mac/super/" with "/usr/bin/"

**Comment by YoshitakaMo** [comment]
This issue occurred on Apple Silicon Mac. I've fixed this issue and updated to version 1.15.0. Please try `brew update && brew install staden-io-lib`.

**Comment by nekoqdesu** [comment]
Thank you!iPhoneから送信2024/03/03 1:22、Yoshitaka Moriwaki ***@***.***>のメール:﻿
This issue occurred on Apple Silicon Mac. I've fixed this issue and updated to version 1.15.0. Please try brew update && brew install staden-io-lib.
