### ISSUE TITLE
orthofinder and MCL (markov clustering) does not compile on M1 

### ISSUE THREAD

**Issue by stephrom** [brewsci/homebrew-bio#1698]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:

- [ x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new.
- [x ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)
I'm trying to install orthofinder locally on a Macbook pro M1. All dependencies (diamond, fastme) if installed separately works fine,  except MCL. The diamond and fastme that were installed with orthofinder were pre-compiled executables that didn't work. Creating softlinks pointing to the pre-installed, independently, solved the issue. Except for mcl.
- What happened (include command output)
brew install mcl
==> Downloading https://formulae.brew.sh/api/formula.jws.json
########################################################################################################################################### 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
########################################################################################################################################### 100.0%
==> Fetching brewsci/bio/mcl
==> Downloading https://micans.org/mcl/src/mcl-14-137.tar.gz
Already downloaded: /Users/strom/Library/Caches/Homebrew/downloads/2270c1e35b168dd765d6a0cec7fcbe7de4f6a0f971073bf1caa3e3d44737d6cb--mcl-14-137.tar.gz
==> Installing mcl from brewsci/bio
==> ./configure --enable-blast
Last 15 lines from /Users/strom/Library/Logs/Homebrew/mcl/01.configure:
checking float.h presence... yes
checking for float.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking malloc.h usability... no
checking malloc.h presence... no
checking for malloc.h... no
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for unistd.h... (cached) yes
checking for an ANSI C-conforming const... yes
checking for size_t... yes
checking build system type... configure: error: /bin/sh autofoo/config.sub -apple-darwin23.5.0 failed
configure: WARNING: cache variable ac_cv_build contains a newline

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/brewsci/homebrew-bio/issues

- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

downloading the original : wget https://www.micans.org/mcl/src/mcl-22-282.tar.gz
setenv CC /opt/homebrew/bin/gcc
setenv CPATH /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include

./configure
checking for a BSD-compatible install... /opt/local/bin/ginstall -c
checking whether build environment is sane... yes
/Users/strom/Downloads/mcl-22-282/autofoo/missing: Unknown `--is-lightweight' option
Try `/Users/strom/Downloads/mcl-22-282/autofoo/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
checking for a thread-safe mkdir -p... /opt/local/bin/gmkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking whether make supports the include directive... yes (GNU style)
checking for gcc... /opt/homebrew/bin/gcc
checking whether the C compiler works... no
configure: error: in `/Users/strom/Downloads/mcl-22-282':
configure: error: C compiler cannot create executables
See `config.log' for more details
# Formula additions or changes

There is an issue compiling the code. I guess the same happens when installing from brew

To get formulae added or changed in Brewsci/bio please file a [Pull Request](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md).
[config.log](https://github.com/user-attachments/files/15534933/config.log)

**Comment by YoshitakaMo** [comment]
@stephrom I've updated `mcl.rb` to 22-282. It is now available on M1 Mac. Please try installation!
