### ISSUE TITLE
Migrate tseemann/homebrew-bioinformatics-linux recipes

### ISSUE THREAD

**Issue by tseemann** [brewsci/homebrew-bio#17]
I have been maintaining a tap for "difficult" and "my own packages that update a lot":
https://github.com/tseemann/homebrew-bioinformatics-linux .My goal is to move it to `brewsci/bio`.  

* most of them are Linux and MacOS capable, where possible
* some of them are binaries, as no code available or compiling is really difficult
* some are GUIs which can't have tests as no X11 available at build time
* some are Java

- [x] abricate.rb
- [x] ascp.rb
- [x] bandage.rb
- [x] blast-legacy.rb
- [x] ~~disty.rb~~  # done by @sjackman  #independently
- [x] easel.rb
- [x] figtree.rb 
- [ ] gemma.rb
- [x] gepard.rb
- [ ] gff3toembl.rb
- [x] gzstream.rb
- [ ] indel-seq-gen.rb
- [ ] indelible.rb
- [x] ispcr.rb
- [x] kr.rb
- [x] light-assembler.rb
- [x] lofreq.rb
- [x] magic-blast.rb 
- [x] ~~minia2.rb~~  # conflicts with minia 1.x 
- [x] ngmaster.rb
- [ ] nullarbor.rb
- [x] panito.rb
- [ ] pbsim.rb
- [ ] peat.rb
- [ ] pftools.rb
- [ ] possum-search.rb
- [ ] pplacer.rb
- [ ] rapmap.rb
- [ ] razers.rb
- [ ] rematch.rb
- [ ] roary.rb
- [ ] sabre.rb
- [x] ~~seer.rb~~ # replaced by pyseer
- [x] seqkit.rb
- [x] shovill.rb
- [ ] sibelia.rb
- [x] snippy.rb
- [x] snp-dists.rb
- [ ] snpfinder.rb
- [ ] taco.rb
- [ ] trim-galore.rb
- [x] varsim.rb
- [x] ~~wombac.rb~~ # replaced by snippy
- [ ] xstk.rb

**Comment by sjackman** [comment]
Time to start checking boxes, Torsten! You don't want to make Stalebot angry. 😡

**Comment by sjackman** [comment]
Thanks for the bug report. In the future, please open a new issue. Your issue should be fixed by
https://github.com/tseemann/homebrew-bioinformatics-linux/commit/5c88f9e6c0ec839336ff9c1cfd5361b0e1aefcfb

**Comment by tseemann** [comment]
I think i've migrated everything important.
