### ISSUE TITLE
brewsci/bio/gemmi 0.6.5 did not build  Logs:      /home/vijayverma/.cache/Homebrew/Logs/gemmi/00.options.out      /home/vijayverma/.cache/Homebrew/Logs/gemmi/01.cmake      /home/vijayverma/.cache/Homebrew/Logs/gemmi/01.cmake.cc      /home/vijayverma/.cache/Homebrew/Logs/gemmi/CMakeCache.txt

### ISSUE THREAD

**Issue by vijayverma1** [brewsci/homebrew-bio#1707]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:

- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# Formula additions or changes

To get formulae added or changed in Brewsci/bio please file a [Pull Request](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md).

**Comment by vijayverma1** [comment]
Logs:
     /home/vijayverma/.cache/Homebrew/Logs/gemmi/00.options.out
     /home/vijayverma/.cache/Homebrew/Logs/gemmi/01.cmake
     /home/vijayverma/.cache/Homebrew/Logs/gemmi/01.cmake.cc
     /home/vijayverma/.cache/Homebrew/Logs/gemmi/CMakeCache.txt

**Comment by vijayverma1** [comment]
Hi,I am trying to download coot using home brew, This below command doesnt work -
brew install./coot.rb verbose --debug --keep-tmp --HEAD
error when i use brew gist-logs <formula>
Upload logs for a failed build of formula to a new Gist. Presents an error
message if no logs are found.

      --with-hostname              Include the hostname in the Gist.
  -n, --new-issue                  Automatically create a new issue in the
                                   appropriate GitHub repository after creating
                                   the Gist.
  -p, --private                    The Gist will be marked private and will not
                                   appear in listings but will be accessible
                                   with its link.
  -d, --debug                      Display any debugging information.
  -q, --quiet                      Make some output more quiet.
  -v, --verbose                    Make some output more verbose.
  -h, --help                       Show this message.
Error: invalid option: --keep-tmp
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/parser.rb:328:in `parse_remaining'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/parser.rb:380:in `parse'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/abstract_command.rb:53:in `initialize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11463/lib/types/private/abstract/declare.rb:37:in `new'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11463/lib/types/private/abstract/declare.rb:37:in `block in declare_abstract'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:90:in `<main>'

**Comment by YoshitakaMo** [comment]
Now gemmi has been upgraded to 0.6.6. If you want to install coot, please use `brew install yoshitakamo/bio2/coot`.
