### ISSUE TITLE
gatk and star-aligfner formulas not working

### ISSUE THREAD

**Issue by giuliovn** [brewsci/homebrew-bio#1709]
- [X] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new.
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

### `brew config` and `brew doctor` output
```bash
ubuntu@giulio:~/install-bio$ brew config
HOMEBREW_VERSION: 4.3.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1c98a33a376e5b35ebc801d0f7d6ba7b9eb118ac
Last commit: 12 hours ago
Core tap JSON: 08 Jul 13:04 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_BROWSER: /home/ubuntu/.vscode-server/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/bin/helpers/browser.sh
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 2
Homebrew Ruby: 3.3.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/bin/ruby
CPU: dual-core 64-bit skylake
Clang: N/A
Git: 2.25.1 => /bin/git
Curl: 7.68.0 => /bin/curl
Kernel: Linux 5.15.0-1064-aws x86_64 GNU/Linux
OS: Ubuntu 20.04.6 LTS (focal)
Host glibc: 2.31
/usr/bin/gcc: 9.4.0
/usr/bin/ruby: N/A
glibc: 2.35_1
gcc@11: N/A
gcc: 14.1.0_1
xorg: N/A
ubuntu@giulio:~/install-bio$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  star-aligner
  gatk

Warning: Some installed formulae are missing dependencies.
You should `brew install` the missing dependencies:
  brew install bison gettext libpthread-stubs libxml2 m4 openssl@1.1 pkg-config python@3.9 tcl-tk

Run `brew missing` for more details.
```

### What I am trying to do
I want to install `gatk` and `star-aligner`.
I have the latest brew version, I added the repo with `brew tap brewsci/bio` and installed with `brew installl gatk` and `brew install star-aligner`

#### `brew install star-aligner`
> ==> Auto-updating Homebrew...
> Adjust how often this is run with HOMEBREW_AUTO_UPDATE_SECS or disable with
> HOMEBREW_NO_AUTO_UPDATE. Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
> **==> Downloading https://ghcr.io/v2/brewsci/bio/star-aligner/manifests/2.7.10
> curl: (22) The requested URL returned error: 404** 
> 
> ==> Fetching brewsci/bio/star-aligner
> ==> Downloading https://ghcr.io/v2/brewsci/bio/star-aligner/blobs/sha256:aff1dc125eb4d50961b110519420cf840c603cf29f2aa58a21aee1427d1f3799
> Already downloaded: /home/ubuntu/.cache/Homebrew/downloads/8cce0b5345d680faa052c9b1d9021b3a2f8096fc925081c7403d87e6df69751b--star-aligner--2.7.10.x86_64_linux.bottle.tar.gz
> ==> Installing star-aligner from brewsci/bio
> ==> Pouring star-aligner--2.7.10.x86_64_linux.bottle.tar.gz
> Error: /home/linuxbrew/.linuxbrew/Cellar/star-aligner/2.7.10 is not a directory

The curl failure seems suspicious, and interestingly, there is a directory parallel to the one in the error, but with a different version: **/home/linuxbrew/.linuxbrew/Cellar/star-aligner/2.7.10a+220818**

#### `brew install gatk`

> ==> Auto-updating Homebrew...
> Adjust how often this is run with HOMEBREW_AUTO_UPDATE_SECS or disable with
> HOMEBREW_NO_AUTO_UPDATE. Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
> **==> Downloading https://ghcr.io/v2/brewsci/bio/gatk/manifests/4.3.0.0
> curl: (22) The requested URL returned error: 404 **
> 
> ==> Fetching brewsci/bio/gatk
> ==> Downloading https://ghcr.io/v2/brewsci/bio/gatk/blobs/sha256:e4b4117555b904663ca90c00945cc29f7767742bb6c3a37078c0f077db52261d
> Already downloaded: /home/ubuntu/.cache/Homebrew/downloads/829cdef5a7d5e3932936971a5e6aedbf6053bb41d7ec4e7f459c345901d1b741--gatk--4.3.0.0.x86_64_linux.bottle.tar.gz
> ==> Installing gatk from brewsci/bio
> ==> Pouring gatk--4.3.0.0.x86_64_linux.bottle.tar.gz
> Error: /home/linuxbrew/.linuxbrew/Cellar/gatk/4.3.0.0 is not a directory

The curl failure seems suspicious, and interestingly, there is a directory parallel to the one in the error, but with a different version: **/home/linuxbrew/.linuxbrew/Cellar/gatk/4.2.0.0**

**Comment by nickjhathaway** [comment]
Running into the same issue for gatk: 

`brew config` and `brew doctor` output

```bash
[17:37]nhathawa@pbaileyubwebcit:~$ brew config
HOMEBREW_VERSION: 4.3.9-28-g302a2b3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 302a2b3aae2e9c7fecf2c21a55af5b3a2ec5804e
Last commit: 2 hours ago
Core tap JSON: 10 Jul 21:36 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 24
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/bin/ruby
CPU: 24-core 64-bit icelake
Clang: N/A
Git: 2.45.2 => /home/linuxbrew/.linuxbrew/bin/git
Curl: 7.81.0 => /bin/curl
Kernel: Linux 5.15.0-113-generic x86_64 GNU/Linux
OS: Ubuntu 22.04.4 LTS (jammy)
Host glibc: 2.35
/usr/bin/gcc: 11.4.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@11: N/A
gcc: 14.1.0_1
xorg: N/A
```

```bash
[17:37]nhathawa@pbaileyubwebcit:~$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  openssl@1.1
  python@3.8

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  gatk

Warning: Broken symlinks were found. Remove them with `brew cleanup`:
  /home/linuxbrew/.linuxbrew/opt/gatk
  /home/linuxbrew/.linuxbrew/var/homebrew/linked/gatk
```

**Comment by YoshitakaMo** [comment]
Now gatk 4.6.0.0 and star-aligner 2.7.11b are available. Please try the installation.

**Comment by giuliovn** [comment]
Thanks, the installation works fine now.
