### ISSUE TITLE
Missing BTL software 

### ISSUE THREAD

**Issue by gejessicama** [brewsci/homebrew-bio#178]
The following software mentioned on the BTL website is not in brewsci/bio:
@sjackman 

**In brewsci/science, not brewsci/bio**
- BioBloom Tools
- DIDA
- Kollector
- LINKS
- TransABySS

**Not in homebrew-core, brewsci/bio, or brewsci/science**
- ARKS
- ChopStitch
- NanoSim
- ntHash
- PAVFinder 
- Cobbler/RAILS
- Tigmint
- xmatchview

**Comment by tseemann** [comment]
What is the "BTL website" ?

**Comment by sjackman** [comment]
My supervisor Inanc Birol's lab is called the Bioinformatics Technology Lab (BTL) at BC Cancer. Jessica is developing our web site. We'll finally have a web site! Check out the demo here https://bcgsc.github.io/btl/
Comments and feedback are welcome!

**Comment by sjackman** [comment]
@gejessicama Could you please put the same grey box around `Photo by Martin Krzywinski` that surrounds the other text on the photo?
