### ISSUE TITLE
[Questions] how the bottling process work

### ISSUE THREAD

**Issue by randy3k** [brewsci/homebrew-bio#19]
Hi @sjackman,

I am a bit curious how the bottling process in CircleCI works. Specifically, 

1. how CircleCI is authenticated to push to LinuxbrewTestBot/homebrew-bio? I cannot find any corresponding token in the circle config file. (or it is done in the webhook?)

2. how the webhook https://p4142ivuwk.execute-api.us-west-2.amazonaws.com/prod/ci-upload uploads bottles and how can (or is it possible for) other taps use this webhook to upload to their own bintray account?

**Comment by sjackman** [comment]
Bottles are transferred by the webhook. I wasn't able to figure out a way to add the credentials to CircleCI and build fork pull requests securely without exposing those credentials. That was with CircleCI 1.0. It's possible that CircleCI 2.0 could do this. I haven't investigated. The webhook is a small bot running on AWS Lambda: https://github.com/Linuxbrew/linuxbrew-lambda

**Comment by sjackman** [comment]
I'd suggest first investigating whether you can transfer bottles securely somehow using CircleCI 2.0. If it's possible, it'd be much simpler than what I'm doing with AWS Lambda. If that doesn't pan out for you, come back to this, and we can discuss my AWS Lambda solution more.

**Comment by MikeMcQuaid** [comment]
@sjackman @randy3k Also if either of you figure out a solution that could be genericised to allow building bottles on the free CircleCI workers: shout and I want to build that into our tap documentation.

**Comment by sjackman** [comment]
You can use CircleCI to build bottles now if the developer (rather than a bot) downloads the bottles from CircleCI AWS S3 and uploads them to Bintray. For example…
```sh
brew tap linuxbrew/developer
brew pull-circle --ci-upload https://github.com/foo/homebrew-bar/pull/123
brew pull --bottle https://github.com/foo/homebrew-bar/pull/123
```
@randy3k Would you like to give this a shot?

You could in principle serve the bottles directly from CircleCI AWS S3, with the caveat being that CircleCI doesn't guarantee that the bottles will remain indefinitely.

**Comment by sjackman** [comment]
@MikeMcQuaid Would you like me to open a PR to contribute `brew pull-circle` to Homebrew/test-bot, Homebrew/brew, or Homebrew/dev-tools?
https://github.com/Linuxbrew/homebrew-developer/blob/master/cmd/brew-pull-circle.rb

**Comment by MikeMcQuaid** [comment]
@sjackman I'd rather wait until/if we figure out a workflow that doesn't require manual command usage. Thanks, though!

**Comment by sjackman** [comment]
It could be rolled into an option of `brew pull --bottle`:
```sh
brew pull --bottle --circle https://github.com/foo/homebrew-bar/pull/123
```

**Comment by randy3k** [comment]
You are right. It was uploaded because I am using https://github.com/tcnksm/ghr and it uploads everything in a directory in default.
