### ISSUE TITLE
minimap2 package doesn't include misc/ paftools

### ISSUE THREAD

**Issue by tseemann** [brewsci/homebrew-bio#191]
@sjackman The minimap2 pkg doesn't have `misc` in it
this has `paftools.js` which Heng says needs `k8` to run?
details at https://github.com/lh3/minimap2/tree/master/misc
opinion?
it's a useful tool for doing numcer+show-snps type stuff!

**Comment by sjackman** [comment]
I'm fine with including the `misc` directory.
```ruby
prefix.install "misc"
```
Do you want to bump the revision and fix it now, or wait for the next release?
