### ISSUE TITLE
coot start up error

### ISSUE THREAD

**Issue by diffracteD** [brewsci/homebrew-bio#1963]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:

- [x ] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new.
- [x ] Ran `brew update` and retried your prior step?
- [ x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

Hi,
I was trying to install coot using brew on my Mac M2.
So I ran `brew install brewsci/bio/coot` and it got coot installed without any error.
However, when I'm trying to run it, it shows me the following error:
```

╰─$ coot
dyld[78507]: Library not loaded: /opt/homebrew/opt/boost-python3/lib/libboost_python312.dylib
  Referenced from: <25E2FF9E-2E79-3062-AB22-C12AA14C4F5E> /opt/homebrew/Cellar/coot/1.1.11_1/libexec/MacCoot
  Reason: tried: '/opt/homebrew/opt/boost-python3/lib/libboost_python312.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/boost-python3/lib/libboost_python312.dylib' (no such file), '/opt/homebrew/opt/boost-python3/lib/libboost_python312.dylib' (no such file), '/opt/homebrew/Cellar/boost-python3/1.87.0_1/lib/libboost_python312.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/boost-python3/1.87.0_1/lib/libboost_python312.dylib' (no such file), '/opt/homebrew/Cellar/boost-python3/1.87.0_1/lib/libboost_python312.dylib' (no such file)
/opt/homebrew/bin/coot: line 7: 78507 Abort trap: 6           ${exec_prefix}/libexec/MacCoot "$@"


```
Not sure how to proceed from here.
Any advice would be appreciated.

Thanks.

**Comment by YoshitakaMo** [comment]
Just 8 hours ago, `libboost-python312.dylib` was deprecated. See https://github.com/Homebrew/homebrew-core/commit/77e0e9be246326bbdda79628f6f6cc3771442e3d 
Since Homebrew-core is now transitioning to Python 3.13, 3.12 and 3.13 libraries are mixed. However, mixed libraries do harm to the rendering of Coot. 
This tracking is very painful, but I shall work on fixing it.

**Comment by YoshitakaMo** [comment]
I've pushed the fixed one. Please try again, `brew update ; brew upgrade ; brew install brewsci/bio/coot` !
