### ISSUE TITLE
[Question] Non-canonical repositories

### ISSUE THREAD

**Issue by lmrodriguezr** [brewsci/homebrew-bio#23]
Hello,

I'm working on a formula for scythe. As it happens, scythe was originally developed at vsbuffalo/scythe, but the official repo is the fork ucdavis-bioinformatics/scythe. This causes `brew audit --new-formula` to hurl, is it safe to ignore that error for new formulae in brewsci/bio? Any workaround?

**Comment by lmrodriguezr** [comment]
By the way, this is the error message:
```
brewsci/bio/scythe:
  * GitHub fork (not canonical repository)
Error: 1 problem in 1 formula
```

**Comment by sjackman** [comment]
Currently a failed `brew audit` prevents the bottles from being collected and deployed.
See https://github.com/brewsci/homebrew-bio/blob/master/.circleci/config.yml#L94

**Comment by sjackman** [comment]
@vsbuffalo Hi, Vince. Currently `ucdavis-bioinformatics/scythe` shows up as a fork of `vsbuffalo/scythe`, though I understand that `ucdavis-bioinformatics` is the canonical repo now. There's two ways I can see to resolve this:

1. Delete the repo `ucdavis-bioinformatics/scythe` and then transfer `vsbuffalo/scythe` to the `ucdavis-bioinformatics` organization.
2. Delete the repo `vsbuffalo/scythe` and then if you like fork `ucdavis-bioinformatics/scythe`

Do either of these options work for you?

**Comment by vsbuffalo** [comment]
I'm the original developer and still follow development (though much less active that I used to be), so IMO I think they should be submitting pull requests and `vsbuffalo/scythe` should be the original repo. I've reviewed other pull requests in the past. What do you think @najoshi? 

I don't see why either 1 or 2 is necessary over having `ucdavis-bioinformatics/scythe` just submit pull requests — is there a reason?

**Comment by sjackman** [comment]
Thanks for your quick response, Vince. Could you tag a stable release of `scythe`?

**Comment by vsbuffalo** [comment]
Let's get a pull request first, and then I'll tag a stable release, yes? @najoshi
