### ISSUE TITLE
Question: How should OpenMP requirements be handled?

### ISSUE THREAD

**Issue by lmrodriguezr** [brewsci/homebrew-bio#270]
Hi,

I'm looking at the specific case of [clustal-omega](https://github.com/brewsci/homebrew-bio/blob/master/Formula/clustal-omega.rb). ClustalOmega [supports multi-threading given support for OpenMP](http://www.clustal.org/omega/INSTALL), is there a way to turn this on?

I'm guessing one way would be to add an `--with-omp` option in the formula and `require :libomp` if the option is passed, but I didn't want to go straight into a pull request if that's not a canonical pattern.

Thanks!
-Miguel

**Comment by lmrodriguezr** [comment]
Oh, that's cool!

Does that mean that if I `brew install libomp` and then reinstall clustal-omega, I'll have access to the `--threads` option? Wouldn't that implicit requirement somehow break the bottles? (e.g., the bottles will never have support for `--threads` even if openmp is installed)

**Comment by sjackman** [comment]
Are you using Linux or macOS? `libomp` is needed on neither, as we use GCC's implementation of OpenMP rather than LLVM's.

**Comment by sjackman** [comment]
@lmrodriguezr Would you like to open a PR to enable OpenMP that adds to the formula…
https://github.com/brewsci/homebrew-bio/blob/master/Formula/clustal-omega.rb
```ruby
# OpenMP support is optional.
fails_with :clang # needs openmp
depends_on "gcc" if OS.mac?  # for openmp
```
