### ISSUE TITLE
scripts/nucmer.pl.~1.5.~  in mummer bottle

### ISSUE THREAD

**Issue by tseemann** [brewsci/homebrew-bio#35]
Is this an accident?

```
% brew ls -v mummer | grep '~'
/home/linuxbrew/.linuxbrew/Cellar/mummer/3.23_3/scripts/nucmer.pl.~1.5.~
```

**Comment by sjackman** [comment]
I guess that file is included in the MUMmer source code. Call it an upstream bug? I plan to package MUMmer 4. I'll take a look for `*~*` when I do.
