### ISSUE TITLE
List of formula *maybe* needing perl bumping

### ISSUE THREAD

**Issue by tseemann** [brewsci/homebrew-bio#414]
@sjackman @suujia 

`grep PERL *rb | grep env | sort | sed 's/^/* \[ \] /'`   

* [x] abricate.rb:      (bin/name).write_env_script("#{libexec}/bin/#{name}", :PERL5LIB => ENV["PERL5LIB"])
* [x] bioperl.rb:    bin.env_script_all_files libexec, "PERL5LIB" => ENV["PERL5LIB"]
* [x] bioperl.rb:      (bin/name).write_env_script executable, :PERL5LIB => ENV["PERL5LIB"]
* [x] circos.rb:    (bin/"circos").write_env_script("#{libexec}/bin/circos", :PERL5LIB => ENV["PERL5LIB"])
* [x] edirect.rb:      (bin/name).write_env_script(script, :PERL5LIB => ENV["PERL5LIB"])
* [x] lrsim.rb:    (bin/"simulateLinkedReads").write_env_script(prefix/"simulateLinkedReads.pl", :PERL5LIB => ENV["PERL5LIB"])
* [x] maker.rb:      (bin/name).write_env_script("#{libexec}/bin/#{name}", :PERL5LIB => ENV["PERL5LIB"])
* [x] meme.rb:      (bin/"meme").write_env_script(libexec/"bin/meme", :PERL5LIB => ENV["PERL5LIB"])
* [x] mlst.rb:    (bin/"mlst").write_env_script("#{libexec}/bin/mlst", :PERL5LIB => ENV["PERL5LIB"])
* [x] repeatmasker.rb:      (bin/"RepeatMasker").write_env_script(libexec/"RepeatMasker", :PERL5LIB => ENV["PERL5LIB"])
* [x] simulate-pcr.rb:    bin.env_script_all_files libexec, "PERL5LIB" => ENV["PERL5LIB"]
* [x] transdecoder.rb:        (bin/executable).write_env_script(prefix/executable, :PERL5LIB => ENV["PERL5LIB"])

**Comment by sjackman** [comment]
```
$ head -n1 /home/linuxbrew/.linuxbrew/Cellar/lrsim/1.0/simulateLinkedReads.pl
#!/usr/bin/env perl
```
`lrsim` seems okay.

**Comment by hwalinga** [comment]
I think the issue I had with edirect is related to this, so I thought I post it here instead of opening a new issue. 

I got: 

```
Parser.c: loadable library and perl binaries are mismatched (got handshake key 0xce00080, needed 0xcd00080)
```

However, when I installed from source edirect worked fine. So for anybody stumbling upon this issue looking for a work-around: 

```
brew reinstall --build-from-source edirect
```

**Comment by jonchang** [comment]
@hwalinga can you open a pull request that bumps the `revision` of `edirect`? Thanks!

**Comment by hwalinga** [comment]
@jonchang I know too little about Perl or Linuxbrew to know what is exactly going on, and why the --build-from-source flag fixed it. Sorry.

**Comment by sjackman** [comment]
@hwalinga Try running `brew bump-revision edirect` to open a PR to rebuild a new bottle for `edirect`.

**Comment by sjackman** [comment]
All of these issues have now been addressed.

**Comment by tseemann** [comment]
@sjackman can we close this now then?

**Comment by sjackman** [comment]
@dmohadjel Can you test that each of the above formulae work using interactively `brew install foo` and `brew linkage --check foo` and `brew test foo`?

**Comment by dmohadjel** [comment]
@sjackman I tested all the formulae and most were successful aside from the following:

Running `brew test circos` would return
```
==> /home/dmohadjel/.linuxbrew/Cellar/circos/0.69-6_1/bin/circos -conf /home/dmohadjel/.linuxbrew/Cellar/circos/0.69-6_1/libexec/example/etc/circos.conf -debug_group summary,timer
Last 15 lines from /home/dmohadjel/.cache/Homebrew/Logs/circos/test.01.circos:
2019-07-17 12:17:51 -0700

/home/dmohadjel/.linuxbrew/Cellar/circos/0.69-6_1/bin/circos
-conf
/home/dmohadjel/.linuxbrew/Cellar/circos/0.69-6_1/libexec/example/etc/circos.conf
-debug_group
summary,timer

Clone.c: loadable library and perl binaries are mismatched (got handshake key 0xce00080, needed 0xcd00080)
Error: brewsci/bio/circos: failed
```
I would not get this error when installing `circos` with `brew install --build-from-source circos`.

Running `brew test lrsim` would return
```
==> /home/dmohadjel/.linuxbrew/Cellar/lrsim/1.0/bin/simulateLinkedReads -h 2>&1
Error: brewsci/bio/lrsim: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <2> expected but was
<1>.
```
Again, I wouldn't get this error when installing with `brew install --build-from-source lrsim`.

Running `brew test mlst` would return
```
==> /home/dmohadjel/.linuxbrew/Cellar/mlst/2.16.1/bin/mlst --version
XS.c: loadable library and perl binaries are mismatched (got handshake key 0xce00080, needed 0xcd00080)
Error: brewsci/bio/mlst: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <0> expected but was
<1>. 
```
And again the error did not occur when installed using `brew install --build-from-source mlst`.

Lastly, I haven't been able to use any of the commands with `transdecoder`. I get the following error every time:
```
Error: Unsupported type NilClass for nil
```

**Comment by sjackman** [comment]
Great. Thanks, Dara! Please open one PR for each of these failed formulae to bump the revision.

**Comment by sjackman** [comment]
Use `brew install -sdv transdecoder` and see if you can get a backtrace to troubleshoot it.

**Comment by dmohadjel** [comment]
@sjackman I still get this error when trying `brew install -sdv transdecoder`, and I don't arrive to the prompt after failing. 
```
Error: Invalid formula: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/brewsci/homebrew-bio/Formula/transdecoder.rb
Unsupported type NilClass for nil
```
However, the installation will be successful if I run 
```
brew install -sdv https://raw.githubusercontent.com/dmohadjel/homebrew-bio/transdecoder-5.5.0/Formula/transdecoder.rb
```

**Comment by sjackman** [comment]
`brew tap brewsci/bio` is failing for me now.
```
==> Tapping brewsci/bio
Cloning into '/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/brewsci/homebrew-bio'...
Error: Invalid formula: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/brewsci/homebrew-bio/Formula/transdecoder.rb
Unsupported type NilClass for nil
Error: Cannot tap brewsci/bio: invalid syntax in tap!
```
I'm not entirely sure when this issue started. Perhaps there has been a recent pull request to Homebrew/brew to cause this breakage. I don't have time at the moment to look into it. I've opened PR https://github.com/brewsci/homebrew-bio/pull/699 to work around the issue.
