### ISSUE TITLE
mlst 2.14 - weird perl script ends in bin/

### ISSUE THREAD

**Issue by tseemann** [brewsci/homebrew-bio#415]
This is a script from `Module::Build` !

`/home/linuxbrew/.linuxbrew/Cellar/mlst/2.15/libexec/bin/config_data`

=>

`/home/linuxbrew/.linuxbrew/opt/perl/bin/config_data`

I have that last dir in my PATH because not everthing gets put in brew/bin 

So this could not really be a problem for anyone else, but probably pioints to issues in some of the Perl module recipes in CPAN.

**Comment by sjackman** [comment]
This `config_data` script doesn't get installed on macOS. Perhaps `Module::Build` is already installed on macOS, so it doesn't get installed. I don't think there's a bug here, but good to know.
