### ISSUE TITLE
What are motivations for building your own bottles?

### ISSUE THREAD

**Issue by TheSriram** [brewsci/homebrew-bio#440]
Hey,

I came here from [Discourse - Custom taps successfully using bottles](https://discourse.brew.sh/t/any-custom-taps-successfully-using-bottles/2397) and what I'm trying to understand is what is the particular value you are deriving from building your own bottles rather than building from source.

Is it just driving towards a faster installation time? What were the other factors that influenced you while choosing to enable building of bottles for the software vended through your tap.

**Comment by TheSriram** [comment]
Thanks for that reply. 💯 

I see in [config.yml](https://github.com/brewsci/homebrew-bio/blob/master/.circleci/config.yml) file, that you have some git config setup for name and email, is that any sort of pre-requisite?

I also see: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME being used, are they env vars that are being passed in? are they current repo name and user name?

```
brew test-bot --skip-setup --or-later --bintray-org=linuxbrew --root-url=https://linuxbrew.bintray.com/bottles-bio --git-name=LinuxbrewTestBot --git-email=testbot@linuxbrew.sh
```

does that automatically trigger an upload to https://linuxbrew.bintray.com/bottles-bio ? for all mac distros?

do you then retroactively rewrite your formula with the sha and root_url?

I know its a lot of questions, just trying to make sure assumptions are correct 😄

**Comment by sjackman** [comment]
> I see in config.yml file, that you have some git config setup for name and email, is that any sort of pre-requisite?

**Comment by sjackman** [comment]
> I also see: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME being used, are they env vars that are being passed in? are they current repo name and user name?

They're environment variables predefined by CircleCI.
```
CIRCLE_PROJECT_USERNAME=brewsci
CIRCLE_PROJECT_REPONAME=hombrew-bio
```
See https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables

**Comment by sjackman** [comment]
> does that automatically trigger an upload to https://linuxbrew.bintray.com/bottles-bio ? for all mac distros?

Only macOS Sierra, and the bottle is tagged as `:sierra_or_later`.

**Comment by sjackman** [comment]
> do you then retroactively rewrite your formula with the sha and root_url?

An automated script does that.
```sh
brew test-bot --ci-upload
```
We're running that web service on AWS Lambda. See https://github.com/linuxbrew/linuxbrew-lambda
You can just run `brew pull-circle --ci-upload` manually though before pulling the PR with `brew pull --bottle`

**Comment by sjackman** [comment]
What's the GitHub repo for your tap? How many formulae are there in it? Where would you like to store your bottles? Homebrew uses Bintray, and that's a good option. You can also store the bottles on GitHub, which is a good option if you only have a small handful of formulae. Any site with public HTTP access could work though.

**Comment by TheSriram** [comment]
https://github.com/TheSriram/homebrew-aws-sam-cli

I ended up hosting on bintray as well.

**Comment by sjackman** [comment]
If you change
```ruby
sha256 "…" => :sierra
```
to
```ruby
sha256 "…" => :sierra_or_later
```
that bottle will be used on macOS 10.12 (Sierra) and up, after confirming of course that the same bottle does in fact work on High Sierra and Mojave.
