### ISSUE TITLE
How the sha256 values come from in section containing 'root_url'

### ISSUE THREAD

**Issue by shenwei356** [brewsci/homebrew-bio#442]
Hi all, I'm fresh new to brew/linuxbrew and I'm trying to update the seqkit fomula, but I can't figure out how to compute following sha256 values after searching the issues and official site of linuxbrew.

```
  bottle do
    root_url "https://linuxbrew.bintray.com/bottles-bio"
    cellar :any_skip_relocation
    sha256 "7a69ce7a8b1c53858005754c4f3725262a0539166c3fcc316f2ac25f422f0363" => :sierra_or_later
    sha256 "c17453614853dcb7bf49d94c3f395f9b4fb2c162c4667adfe0d73b0988621c82" => :x86_64_linux
  end
```

Please help.

Wei.

**Comment by sjackman** [comment]
You do need to update the sha256 of the source tarball, but you don't need to update the bottle section at all. It will be updated automatically once the binary bottles are rebuilt.

**Comment by shenwei356** [comment]
Oh I see, thank you Shaun.

**Comment by sjackman** [comment]
No worries!
