### ISSUE TITLE
Create a badge to reflect a built package with its version number

### ISSUE THREAD

**Issue by pjotrp** [brewsci/homebrew-bio#476]
As brought up in https://github.com/brewsci/homebrew-bio/pull/469 it would be really nice to have a Travis-CI styled badge which shows the version number of the brew package. E.g.

[![Build Status](https://travis-ci.org/genetics-statistics/GEMMA.svg?branch=master)](https://travis-ci.org/genetics-statistics/GEMMA)

I am surprised it does not exist!

**Comment by sjackman** [comment]
You can make a badge using https://shields.io:
https://img.shields.io/badge/🍺brew-sambamba--0.6.8-brightgreen.svg
<img src="https://img.shields.io/badge/🍺brew-sambamba--0.6.8-brightgreen.svg"></img>

**Comment by mbhall88** [comment]
To clarify, it doesn't seem like you can generate a badge that auto-updates the most recent version though.  
There was some discussion about this here https://github.com/badges/shields/issues/4847, but that was over a year ago.
