### ISSUE TITLE
treePL installation does not work properly

### ISSUE THREAD

**Issue by gavrucent** [brewsci/homebrew-bio#481]
I am trying to install treePL on MacOS High Sierra 10.13.6.
I installed Homebrew and then installed treePL with
brew install brewsci/bio/treepl

I tried to run the provided tests to make sure it works:

brew test -v treepl

I am getting the following error: 
==> /usr/local/Cellar/treepl/2017.05.23/bin/treePL clock.cppr8s
dyld: Library not loaded: /usr/local/opt/gcc/lib/gcc/7/libgomp.1.dylib
  Referenced from: /usr/local/Cellar/treepl/2017.05.23/bin/treePL
  Reason: image not found
Error: brewsci/bio/treepl: failed
undefined method `map' for nil:NilClass
Did you mean?  tap

I would appreciate any help or suggestions. I am very new to this and just need this program for my research, but it looks like I cannot even install it properly.

**Comment by sjackman** [comment]
Fixed by PR https://github.com/brewsci/homebrew-bio/pull/482
