### ISSUE TITLE
pymol: Error: unknown version :x86_64_linux

### ISSUE THREAD

**Issue by JamesABaker** [brewsci/homebrew-bio#501]
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new or https://github.com/Linuxbrew/brew/issues/new.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)

**Installing pymol.**

- What happened (include command output)

**Unknown version error. Output below.**

- What you expected to happen

**Clean install. Matplotlib and bioperl installed well.**

- Step-by-step reproduction instructions (by running `brew install` commands)

See below

      ➜  ~ brew install pymol
      ==> Installing pymol from brewsci/bio
      Error: unknown version :x86_64_linux
      Please report this bug:
        https://docs.brew.sh/Troubleshooting
      /usr/local/Homebrew/Library/Homebrew/os/mac/version.rb:23:in `block in from_symbol'
      /usr/local/Homebrew/Library/Homebrew/os/mac/version.rb:22:in `fetch'
      /usr/local/Homebrew/Library/Homebrew/os/mac/version.rb:22:in `from_symbol'
      /usr/local/Homebrew/Library/Homebrew/extend/os/mac/utils/bottles.rb:60:in `block in find_older_compatible_tag'
      /usr/local/Homebrew/Library/Homebrew/extend/os/mac/utils/bottles.rb:53:in `each'
      /usr/local/Homebrew/Library/Homebrew/extend/os/mac/utils/bottles.rb:53:in `find'
      /usr/local/Homebrew/Library/Homebrew/extend/os/mac/utils/bottles.rb:53:in `find_older_compatible_tag'
      /usr/local/Homebrew/Library/Homebrew/extend/os/mac/utils/bottles.rb:31:in `find_matching_tag'
      /usr/local/Homebrew/Library/Homebrew/utils/bottles.rb:94:in `fetch_checksum_for'
      /usr/local/Homebrew/Library/Homebrew/software_spec.rb:381:in `checksum_for'
      /usr/local/Homebrew/Library/Homebrew/software_spec.rb:368:in `tag?'
      /usr/local/Homebrew/Library/Homebrew/software_spec.rb:96:in `bottled?'
      /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/forwardable.rb:202:in `bottled?'
      /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:92:in `pour_bottle?'
      /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:469:in `expand_dependencies'
      /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:381:in `compute_dependencies'
      /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:142:in `verify_deps_exist'
      /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:135:in `prelude'
      /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:324:in `install_formula'
      /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:256:in `block in install'
      /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:254:in `each'
      /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:254:in `install'
      /usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'

      ➜  ~ brew config
      HOMEBREW_VERSION: 1.8.0
      ORIGIN: https://github.com/Homebrew/brew
      HEAD: fdd8e9b7cf1e53322492e1e90f685c19bdfde506
      Last commit: 3 days ago
      Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
      Core tap HEAD: b159e521eb4d06eb971df3a2da76ea8c4d36d309
      Core tap last commit: 26 minutes ago
      HOMEBREW_PREFIX: /usr/local
      CPU: quad-core 64-bit haswell
      Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
      Clang: 10.0 build 1000
      Git: 2.17.1 => /Library/Developer/CommandLineTools/usr/bin/git
      Curl: 7.54.0 => /usr/bin/curl
      Java: 11.0.1
      macOS: 10.14-x86_64
      CLT: 10.0.0.0.1.1535735448
      Xcode: N/A
      XQuartz: 2.7.11 => /opt/X11

      ➜  ~ brew doctor
      Your system is ready to brew.

      ➜  ~ brew gist-logs pymol    
      Error: No logs.

**Comment by sjackman** [comment]
I believe this bug affects Homebrew/brew 1.8.0, but is not present in 1.7.7, and has been fixed in master. Try…
```sh
HOMEBREW_DEVELOPER=1 brew update
brew install pymol
```

**Comment by sjackman** [comment]
Closing this issue, but please do comment if the above suggestion does not resolve your issue.

**Comment by JamesABaker** [comment]
> I believe this bug affects Homebrew/brew 1.8.0, but is not present in 1.7.7, and has been fixed in master. Try…
> 
> ```shell
> HOMEBREW_DEVELOPER=1 brew update
> brew install pymol
> ```

This fixed the issue. Thanks very much, @sjackman.

**Comment by sjackman** [comment]
Glad to hear it worked!
