### ISSUE TITLE
Can't tap brewsci/bio because of invalid formulae

### ISSUE THREAD

**Issue by pooranis** [brewsci/homebrew-bio#548]
- [NA] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new or https://github.com/Linuxbrew/brew/issues/new.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [NA] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

I am trying to add brewsci/bio as a tap on a machine running MacOS Mojave 10.14.2.
Running `brew tap brewsci/bio` resulted in many errors saying formulae are invalid mostly due to `needs :cxx11` and similar statements in the formulae which are disabled (since [homebrew 1.9.0](https://brew.sh/2019/01/09/homebrew-1.9.0/)?) [gist of output](https://gist.github.com/pooranis/6e1a98299237acc7ae1e1dd08f9606b3#file-gistfile1-txt).

Here is my brew config:
```bash
$ brew config
HOMEBREW_VERSION: 1.9.3-71-g3bdc4c2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3bdc4c294da1d1cea71d63984c6ecb1417bff544
Last commit: 5 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 87bcb21df821b2c719cf0dd892dea48195bf5df9
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_LOGS: ~/Library/Logs/Homebrew
HOMEBREW_NO_INSTALL_CLEANUP: TRUE
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.20.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.2-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: N/A
CLT headers: 10.1.0.0.1.1539992718
XQuartz: 2.7.11 => /opt/X11

$ brew doctor
Your system is ready to brew.
```

**Comment by sjackman** [comment]
Thanks for the bug report, @pooranis! This issue is resolved by commits 2963eedb076000a973b31a548c3875f3231e5530 and 07cdffa0c403ec4d4105bbbbf7a697af90cc6e4b.
