### ISSUE TITLE
problem on recent pymol update script

### ISSUE THREAD

**Issue by xvrxq52Dm6Pu** [brewsci/homebrew-bio#557]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:

- [o ] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new or https://github.com/Linuxbrew/brew/issues/new.
- [o ] Ran `brew update` and retried your prior step?
- [o ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [o ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [o ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)
update pymol
- What happened (include command output)
failed
- What you expected to happen
success
- Step-by-step reproduction instructions (by running `brew install` commands)
brew install pymol

# Formula additions or changes

To get formulae added or changed in Brewsci/bio please file a [Pull Request](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md).
<img width="573" alt="screen shot 2019-02-16 at 2 24 05 pm" src="https://user-images.githubusercontent.com/40440788/52904187-8e434580-31f6-11e9-9392-939cfc79c6f6.png">

**Comment by sjackman** [comment]
Hi, @xvrxq52Dm6Pu. You had local changes to your `pymol` formula when you ran `brew update` (or it ran automatically). If you do not need these local changes, you can run `brew update-reset`. *Warning*: his command will discard all local changes to all of your taps.
