### ISSUE TITLE
error when install pymol

### ISSUE THREAD

**Issue by richor** [brewsci/homebrew-bio#593]
I'm trying to install pymol on MacOS. 
After "brew install pymol", the downloading is ok, the compiling give a error:
```
clang++ -I/usr/local/opt/freetype/include -std=c++11 -D_PYMOL_LIBPNG -
D_PYMOL_FREETYPE -D_PYMOL_INLINE -D_PYMOL_VMD_PLUGINS 
-D_HAVE_LIBXML -DMMTF_MSGPACK_USE_CPP11 -D_PYMOL_OSX 
-D_PYMOL_NUMPY -Icontrib/uiuc/plugins/include -Iov/src -Ilayer0 -Ilayer1 -Ilayer2 
-Ilayer3 -Ilayer4 -Ilayer5 -Imodules/cealign/src -Ibuild/generated 
-Icontrib/uiuc/plugins/molfile_plugin/src -Icontrib/mmtf-c 
-I/usr/local/Cellar/pymol/2.3.0/libexec/lib/python3.7/site
-packages/numpy/core/include -I/usr/local/include -I/usr/local/include/freetype2 
-I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include
 -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/
python3.7m -c layer2/CifFile.cpp -o build/temp.macosx-10.13-x86_64
-3.7/layer2/CifFile.o -Wno-narrowing -Wno-char-subscripts -ffast-math -funroll
-loops -O3 -fcommon -fno-strict-aliasing

error: command 'clang++' failed with exit status 1
```
Maybe this is because recently change the compiler from gcc to clang?

**Comment by richor** [comment]
I figure it out, it's because the downloading is not correct. Should test the MD5 even find one in cache folder.
Please close this issue.

**Comment by richor** [comment]
It's system based, not a general one.
This error occur at my MBA, not at my iMac.
Still not figure it out.

**Comment by sjackman** [comment]
Please report the output of `brew gist-logs pymol`.

**Comment by richor** [comment]
the gist: 
https://gist.github.com/d444ad85cc6b69aa05b3e844ea1e83e8
I tried again. It always stop at CifFile.o compiling step. 
Maybe it's not a brew problem. I don't know.

**Comment by richor** [comment]
I put the /usr/bin before /usr/local/bin.

**Comment by sjackman** [comment]
Glad to hear that you found the fix. `brew doctor` has helpful suggestions, like this.

**Comment by richor** [comment]
Thank you ! 
@sjackman  I notice that the plugin issue here: https://github.com/schrodinger/pymol-open-source/issues/13. Can you fixed it by modified the pymol.rb?

**Comment by richor** [comment]
Thank you !
@sjackman I notice that the plugin issue here: schrodinger/pymol-open-source#13. Can you fixed it by modifying the pymol.rb file?

**Comment by sjackman** [comment]
Homebrew for macOS does not provide an X11 build of `tcl-tk`. It's not straight forward to change that. Here's the relevant line of code: https://github.com/Homebrew/homebrew-core/blob/963a3c49ce6050b1ee6a891bfe50489f4af59005/Formula/tcl-tk.rb#L74
