### ISSUE TITLE
exonerate: installed version cannot find a pcre symbol

### ISSUE THREAD

**Issue by dbaurain** [brewsci/homebrew-bio#632]
Hi,

I have an issue with the formula for `exonerate` (bottle 2.2.0). `brew` installs it but then I cannot manage to run it due to a missing `pcre` symbol in `glibc`:

`$ brew install exonerate`
`Updating Homebrew...`
`==> Installing exonerate from brewsci/bio`
`==> Downloading https://linuxbrew.bintray.com/bottles-bio/exonerate-2.2.0.x86_64`
`Already downloaded: /home/denis/.cache/Homebrew/downloads/f391fe1196ac8d1bf94979abdfcb1f59c5387129fb9824c88b91de52ce01c217--exonerate-2.2.0.x86_64_linux.bottle.tar.gz`
`==> Pouring exonerate-2.2.0.x86_64_linux.bottle.tar.gz`
`🍺  /home/linuxbrew/.linuxbrew/Cellar/exonerate/2.2.0: 39 files, 17.8MB`

`$ exonerate`
`exonerate: symbol lookup error: /home/linuxbrew/.linuxbrew/lib/libglib-2.0.so.0: undefined symbol: pcre_free`

This is for testing purposes. I use a very fresh install of __Ubuntu 18.04__ running in a VirtualBox on a MacBook Air. I am trying to determine the shortest way to install the Linux dependencies of my own bioinformatics software relying on `exonerate`.

I did try to reinstall `pcre` and `glibc`, and to install `pcre2` with `brew` but this had no effect. Maybe I should install a missing dependency directly using `apt-get`, but I would prefer not to do it.

Thank you in advance for your help,
Denis

- [X] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new or https://github.com/Linuxbrew/brew/issues/new.
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

`$ brew gist-logs exonerate`
`Error: No logs.`

`$ brew doctor`
`Your system is ready to brew.`

`$ brew config`
`HOMEBREW_VERSION: 2.1.2`
`ORIGIN: https://github.com/Homebrew/brew`
`HEAD: 4025eadc2c3b9b71aa7029d7ddc6ede1cb88d482`
`Last commit: 10 days ago`
`Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core`
`Core tap HEAD: 5c629fcf3c632a5dc887d5b36527c9e8031ab718`
`Core tap last commit: 2 hours ago`
`HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew`
`HOMEBREW_CACHE: /home/denis/.cache/Homebrew`
`HOMEBREW_LOGS: /home/denis/.cache/Homebrew/Logs`
`CPU: single-core 64-bit skylake`
`Homebrew Ruby: 2.3.7 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby`
`Clang: N/A`
`Git: 2.17.1 => /usr/bin/git`
`Curl: 7.58.0 => /usr/bin/curl`
`Kernel: Linux 4.18.0-17-generic x86_64 GNU/Linux`
`OS: Ubuntu 18.04.2 LTS (bionic)`
`Host glibc: 2.27`
`/usr/bin/gcc: 7.3.0`
`glibc: N/A`
`gcc: N/A`
`xorg: N/A`

**Comment by sjackman** [comment]
Hi, @dbaurain. Please report the output of…
```sh
realpath /home/linuxbrew/.linuxbrew/lib/libglib-2.0.so.0
realpath /home/linuxbrew/.linuxbrew/lib/libpcre.so.1
ldd /home/linuxbrew/.linuxbrew/bin/exonerate
ldd /home/linuxbrew/.linuxbrew/lib/libglib-2.0.so.0
ldd /home/linuxbrew/.linuxbrew/lib/libpcre.so.1
```

**Comment by dbaurain** [comment]
Hi Shaun,

Thank you for your fast reply.

>realpath /home/linuxbrew/.linuxbrew/lib/libglib-2.0.so.0

/home/linuxbrew/.linuxbrew/Cellar/glib/2.60.2/lib/libglib-2.0.so.0.6000.2

>realpath /home/linuxbrew/.linuxbrew/lib/libpcre.so.1

/home/linuxbrew/.linuxbrew/Cellar/pcre/8.43/lib/libpcre.so.1.2.11

>ldd /home/linuxbrew/.linuxbrew/bin/exonerate

linux-vdso.so.1 (0x00007ffeab5f8000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa752e37000)
libglib-2.0.so.0 => /home/linuxbrew/.linuxbrew/lib/libglib-2.0.so.0 (0x00007fa752af5000)
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa7528d6000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa7524e5000)
/home/linuxbrew/.linuxbrew/lib/ld.so => /lib64/ld-linux-x86-64.so.2 (0x00007fa7531d5000)

>ldd /home/linuxbrew/.linuxbrew/lib/libglib-2.0.so.0

Inconsistency detected by ld.so: dl-version.c: 205: _dl_check_map_versions: Assertion `needed != NULL' failed!

>ldd /home/linuxbrew/.linuxbrew/lib/libpcre.so.1

linux-vdso.so.1 (0x00007ffcb8dd7000)
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fc6fb465000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc6fb074000)
/lib64/ld-linux-x86-64.so.2 (0x00007fc6fb8f6000)

Best regards,
Denis

**Comment by sjackman** [comment]
> `Inconsistency detected by ld.so: dl-version.c: 205: _dl_check_map_versions: Assertion `needed != NULL' failed!`

Well, that's an exciting error message. Googling that error message turns up:
https://github.com/pypa/auditwheel/issues/103
> Update for the weary traveler: You may be using a too old version of patchelf, try compiling it from source and using that instead.

**Comment by dbaurain** [comment]
Well, it's already 0.10 :
`$ patchelf --version`
`patchelf 0.10`

Do you think the error might be due to the virtualization environment?
Otherwise, a fresh Ubuntu 18.04 is pretty vanilla.

**Comment by sjackman** [comment]
I can replicate this issue. The file `/home/linuxbrew/.linuxbrew/Cellar/glib/2.60.2/lib/libglib-2.0.so.0.6000.2` is corrupted when the bottle is poured and relocated using `patchelf 0.10`.

```console
$ ldd /home/linuxbrew/.linuxbrew/lib/libglib-2.
0.so.0
Inconsistency detected by ld.so: dl-version.c: 224: _dl_check_map_versions: Assertion `needed != NULL' failed!
$ patchelf --print-interpreter /home/linuxbrew/.linuxbrew/lib/libglib-2.0.so.0
patchelf: cannot find section '.interp'. The input file is most likely statically linked
```

**Comment by sjackman** [comment]
Try the following workaround.
```sh
brew unlink patchelf
brew install https://raw.githubusercontent.com/Homebrew/linuxbrew-core/1d5b681f01440527bc47b3937f25bee3e82b9169/Formula/patchelf.rb
brew reinstall glib
```
Let me know if that works for you!

**Comment by sjackman** [comment]
This issue should be resolved once PR https://github.com/Homebrew/linuxbrew-core/pull/13149 is merged.

**Comment by dbaurain** [comment]
It works. Thank you very much for the quick fix, Shaun.

**Comment by sjackman** [comment]
No worries at all. Thanks for the bug report. PR https://github.com/Homebrew/linuxbrew-core/pull/13149 has been merged too.
