### ISSUE TITLE
PyMOL 

### ISSUE THREAD

**Issue by TakiWakabayashi** [brewsci/homebrew-bio#661]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:

- [* ] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new or https://github.com/Linuxbrew/brew/issues/new.
- [* ] Ran `brew update` and retried your prior step?
- [ *] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why) To install pymol to mac
- What happened (include command output)
(base) $
(base) $brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Library/Frameworks/Python.framework/Versions/2.7/bin/python2-config
  /Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7-config
  /Library/Frameworks/Python.framework/Versions/2.7/bin/python-config
  /anaconda3/bin/icu-config
  /anaconda3/bin/krb5-config
  /anaconda3/bin/freetype-config
  /anaconda3/bin/xslt-config
  /anaconda3/bin/libpng16-config
  /anaconda3/bin/python3.6m-config
  /anaconda3/bin/libpng-config
  /anaconda3/bin/xml2-config
  /anaconda3/bin/python3-config
  /anaconda3/bin/curl-config
  /anaconda3/bin/ncursesw6-config
  /anaconda3/bin/pcre-config
  /anaconda3/bin/python3.6-config
  /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7-config
  /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7m-config
  /Library/Frameworks/Python.framework/Versions/3.7/bin/python3-config
(base) $

- What you expected to happen  successful install

- Step-by-step reproduction instructions (by running `brew install` commands)

# Formula additions or changes

To get formulae added or changed in Brewsci/bio please file a [Pull Request](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md).

**Comment by jonchang** [comment]
Can you please paste the output of `brew install` and of `brew gist-logs` per the issue template? We can’t help you with figuring out this issue without it.

**Comment by TakiWakabayashi** [comment]
Thanks for your prompt reaction.  I paste the output.

(base) $brew install pymol
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
No changes to formulae.

==> Installing pymol from brewsci/bio
==> Downloading https://github.com/schrodinger/pymol-open-source/archive/v2.3.0.tar.gz
Already downloaded: /Users/WakabaMacPro/Library/Caches/Homebrew/downloads/a51d46dea90ae24d275dac1d9efa7cf70025ab5fed71dc210ce3000d5d65219c--pymol-open-source-2.3.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/53/c0/c7819f0bb2cf83e1b4b0d96c901b85191f598a7b534d297c2ef6dc80e2d3/virtualenv-16.6.0.tar.gz
Already downloaded: /Users/WakabaMacPro/Library/Caches/Homebrew/downloads/6d18e6ad1a4c8e31dfc412cb5513a676119ead57a6ad5c830a0ec57ac08fd763--virtualenv-16.6.0.tar.gz
==> python3 -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/pymol/2.3.0/libexec --install-scripts=/usr/local/Cellar/pymol/2.3.0/libexec/bin --single-version-exter
Last 15 lines from /Users/WakabaMacPro/Library/Logs/Homebrew/pymol/01.python3:
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/usr/local/Cellar/pymol/2.3.0/libexec
--install-scripts=/usr/local/Cellar/pymol/2.3.0/libexec/bin
--single-version-externally-managed
--record=installed.txt

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'setuptools'

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/brewsci/homebrew-bio/issues

These open issues may also help:
PyMOL  https://github.com/brewsci/homebrew-bio/issues/661
(base) $

(base) $brew gist-logs pymol
You can create a new personal access token:
  https://github.com/settings/tokens/new?scopes=gist,public_repo&description=Homebrew
echo 'export HOMEBREW_GITHUB_API_TOKEN=your_token_here' >> ~/.bash_profile

GitHub User: 
Password: 

Error: GitHub Requires authentication:The GitHub credentials in the macOS keychain may be invalid.
Clear them with:
  printf "protocol=https\nhost=github.com\n" | git credential-osxkeychain erase
Or create a personal access token:
  https://github.com/settings/tokens/new?scopes=gist,public_repo&description=Homebrew
echo 'export HOMEBREW_GITHUB_API_TOKEN=your_token_here' >> ~/.bash_profile

**Comment by jonchang** [comment]
Your installation of python 3 is broken somehow. Homebrew packages setuptools with its python so something else is going on. Maybe it has to do with your conda install.

**Comment by sjackman** [comment]
Please surround copied-and-pasted logs with triple back ticks. See [GitHub Help / Quoting Code](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code).

**Comment by TakiWakabayashi** [comment]
Dear Jonathan,

    Thank you very much for your kind consideration.
    I will check this in a couple of days.

   With best regards.
   Taki Wakabayashi


2019年6月21日(金) 2:21 Jonathan Chang <notifications@github.com>:

**Comment by TakiWakabayashi** [comment]
Dear Shaun,

   Thank you very much for your e-mail
   I will surround my future log with triple ticks. Is this
related to the comment of python code?

    Best regards.
   Taki Wakabayashi

2019年6月21日(金) 6:31 Shaun Jackman <notifications@github.com>:

**Comment by sjackman** [comment]
>    I will surround my future log with triple ticks. Is this related to the comment of python code?

All copy-and-paste blocks should be surrounded by triple backticks. You can either type triple backticks, or you can select the lines and select the button above the editor labeled `<>`.

**Comment by TakiWakabayashi** [comment]
Dear Jonathan,

    Thank you very much for your comment.
    I uninstalled python3, and reinstalled it using Homebrew.
    I also updated my .profile file.
    Now I could install PyMOL using $brew install brewsci/bio/pymol
successfully.
    Many thanks again.

   With best regards.

    Taki Wakabayashi

2019年6月21日(金) 2:21 Jonathan Chang <notifications@github.com>:

**Comment by sjackman** [comment]
Excellent! I'm glad to hear it. Thanks for following up, Taki.

**Comment by TakiWakabayashi** [comment]
Dear Shaun,

   Thank you very much for your reply.

   Today, I installed pymol to another MacMini successfully.
When I start up pymol, for the first time using MacMini, it said
'''

    More information can be found at "http://www.pymol.org".



    Enter "help" for a list of commands.

    Enter "help <command-name>" for information on a specific command.


 Hit ESC anytime to toggle between text and graphics.


 Detected OpenGL version 2.1. Shaders available.

 Detected GLSL version 1.20.

 OpenGL graphics engine:

  GL_VENDOR:   Intel Inc.

  GL_RENDERER: Intel Iris OpenGL Engine

  GL_VERSION:  2.1 INTEL-10.18.65

 Detected 4 CPU cores.  Enabled multithreaded rendering.


 ObjectMolecule: Read secondary structure assignments.

 ObjectMolecule: Read crystal symmetry information.

 CmdLoad: PDB-string loaded into object
"Yana_ABCDE_ADPMGPi_real_space_refined_real_space_refined_real_space_refined_real_space_refined-coot-2",
state 1.

PyMOL>sel ser14, resi 14 and chain C
'''

   I wonder why it said "Deleted 4 CPU cores, instead of 2, which my MacMin
has, as shown below.

*Hardware Overview:*


  Model Name: Mac mini

  Model Identifier: Macmini7,1

  Processor Name: Intel Core i5

  Processor Speed: 2.6 GHz

  Number of Processors: 1

  Total Number of Cores: 2

  L2 Cache (per Core): 256 KB

  L3 Cache: 3 MB

  Memory: 8 GB

  Boot ROM Version: MM71.0220.B07

  SMC Version (system): 2.24f32

  Serial Number (system): C07SM4PCG1HW

  Hardware UUID: A1B8B27C-0765-5512-8197-F720DF3CEC00



    This is no problem for me, but I thought it might be useful information
for you.

    With best wishes,
                                Taki Wakabayashi

2019年6月26日(水) 0:13 Shaun Jackman <notifications@github.com>:

**Comment by sjackman** [comment]
Please surround copied-and-pasted logs with triple back ticks. See [GitHub Help / Quoting Code](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code).

**Comment by sjackman** [comment]
Possibly due to hyperthreading. https://en.wikipedia.org/wiki/Hyper-threading
What does `brew config` report?
