### ISSUE TITLE
Compiling viennarna from source fails

### ISSUE THREAD

**Issue by twogee** [brewsci/homebrew-bio#728]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:

- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new or https://github.com/Linuxbrew/brew/issues/new.
- [x] Ran `brew update` and retried your prior step
- [x] Ran `brew doctor`, fixed all issues and retried your prior step
- [x] Ran `brew gist-logs viennarna` and included the [output link](https://gist.github.com/b93bfda7ead89222a12e15026203f44a)

To help us debug your issue please explain:

- What you were trying to do (and why)

Build viennarna from source due to changed dependencies

- What happened (include command output)

The compiler bailed on missing standard include file, though the file was there in the path pointed to by `-I` option

- What you expected to happen

The code should compile 

- Step-by-step reproduction instructions (by running `brew install` commands)

`brew reinstall --build-from-source viennarna`

**Comment by jonchang** [comment]
@twogee can you open a pull request to bump the `revision` of this formula? thanks!

**Comment by sjackman** [comment]
There's also a PR to bump the version of `viennarna` here: https://github.com/brewsci/homebrew-bio/issues/728
