### ISSUE TITLE
minimap2 install error

### ISSUE THREAD

**Issue by dougwyu** [brewsci/homebrew-bio#789]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:

- [X] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new or https://github.com/Linuxbrew/brew/issues/new.
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
No logs
- [X] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

`brew config`
> HOMEBREW_VERSION: 2.1.13
> ORIGIN: https://github.com/Homebrew/brew
> HEAD: aa043c1d678afd26f50156a83417c296cb9d5a4b
> Last commit: 32 hours ago
> 
> Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
> Core tap HEAD: d19a90076976e45bb9eb6b0772f6718793b9ed5d
> Core tap last commit: 79 minutes ago
> HOMEBREW_PREFIX: /usr/local
> HOMEBREW_GITHUB_API_TOKEN: set
> CPU: octa-core 64-bit kabylake
> Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
> Clang: 10.0 build 1001
> Git: 2.23.0 => /usr/local/bin/git
> Curl: 7.54.0 => /usr/bin/curl
> Java: 12.0.1, 1.8.0_92
> macOS: 10.14.6-x86_64
> CLT: 10.3.0.0.1.1562985497
> Xcode: N/A
> CLT headers: 10.3.0.0.1.1562985497
> XQuartz: 2.7.11 => /opt/X11

brew doctor output too big to post.

To help us debug your issue please explain:

i tried:

`brew install brewsci/bio/minimap2`

I got:

> ==> Installing minimap2 from brewsci/bio
> Error: Formulae found in multiple taps:
>        * tseemann/bio/k8
>        * brewsci/bio/k8
> 
> Please use the fully-qualified name (e.g. tseemann/bio/k8) to refer to the formula.

I expected minimap2 installation

# Formula additions or changes

To get formulae added or changed in Brewsci/bio please file a [Pull Request](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md).

**Comment by tseemann** [comment]
You have a very old brew installation. Things have changed. You might have to reinstall from scratch. But you could try:
```
brew untap tseemann/homebrew-bioinformatics-linux
brew unatp homebrew/science
brew tap homebrew/bio
brew update
brew upgrade minimap2
```

**Comment by dougwyu** [comment]
ah. thanks very much!

**Comment by jianshu93** [comment]
It seems the newest version for v2.24 and ARM support is not updated.
