### ISSUE TITLE
No available formula with the name "protobuf@3.1"

### ISSUE THREAD

**Issue by DDashevsky** [brewsci/homebrew-bio#832]
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new or https://github.com/Linuxbrew/brew/issues/new.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

I have been trying unsuccessfully for several days to get Trinity to work on a couple of Macs. I ran into this error on the first one I tried, got stymied and switched to another where I had used it before. I received an [error about the dyld library](https://github.com/brewsci/homebrew-bio/issues/543) even though (to my knowledge) nothing about the computer setup had changed since I last successfully ran Trinity. It was suggested that I upgrade my operating system from OS X 10.12, so I did so and now have OS X 10.14. However I then started receiving the same error I had on the first computer.

When I run`brew install trinity` or `brew install express` (a dependency of Trinity), I run into this: `Error: No available formula with the name "protobuf@3.1"`. I have `protobuf@3.10` installed, but this does not seem to satisfy the requirements. I tried following [the solution here](https://github.com/Homebrew/homebrew-science/issues/3828) and was able to manually install `express` to my `Cellar` and add a symbolic link to `/usr/local/bin`. However, `--without-express` seems not to be supported anymore, so I tried running `brew install trinity --ignore-dependencies` (after checking to make sure I had all the other non-`express` dependencies installed through Homebrew) and got the following output:

>==> Installing trinity from brewsci/bio
>==> Downloading https://linuxbrew.bintray.com/bottles-bio/trinity-2.8.3_1.sierra.bottle.tar.gz
>==> Downloading from https://akamai.bintray.com/5e/5e23769342aadb13867b85f482c8fd7e1cd55cac5a31d21a190217030ac8a756?__gda__=exp=1573727302~hmac=ac1e4915b4d81b9b1f9d236ee26a66d670e837
>######################################################################## 100.0%
>==> Pouring trinity-2.8.3_1.sierra.bottle.tar.gz
>Error: No available formula with the name "protobuf@3.1" 
>Warning: Bottle installation failed: building from source.
>==> Downloading https://github.com/trinityrnaseq/trinityrnaseq/archive/Trinity-v2.8.3.tar.gz
>==> Downloading from https://codeload.github.com/trinityrnaseq/trinityrnaseq/tar.gz/Trinity-v2.8.3
>######################################################################## 100.0%
>==> make all plugins test
>Last 15 lines from /Users/venomlab/Library/Logs/Homebrew/trinity/01.make:
>config.status: creating src/Makefile
>config.status: creating config.h
>config.status: config.h is unchanged
>config.status: executing depfiles commands
>Making install in src
>g++-9 -DHAVE_CONFIG_H -I. -I..    -pedantic -fopenmp -Wall -Wextra -Wno-long-long -Wno-deprecated -m64 -fopenmp -MT ParaFly.o -MD -MP -MF .deps/ParaFly.Tpo -c -o ParaFly.o ParaFly.cpp
>g++-9 -DHAVE_CONFIG_H -I. -I..    -pedantic -fopenmp -Wall -Wextra -Wno-long-long -Wno-deprecated -m64 -fopenmp -MT argProcessor.o -MD -MP -MF .deps/argProcessor.Tpo -c -o argProcessor.o argProcessor.cpp
>mv -f .deps/argProcessor.Tpo .deps/argProcessor.Po
>mv -f .deps/ParaFly.Tpo .deps/ParaFly.Po
>g++-9 -pedantic -fopenmp -Wall -Wextra -Wno-long-long -Wno-deprecated -m64 -fopenmp   -o ParaFly ParaFly.o argProcessor.o  
>test -z "/private/tmp/trinity-20191114-41443-1auzdsk/trinityrnaseq-Trinity-v2.8.3/trinity-plugins/ParaFly-0.1.0/bin" || .././install-sh -c -d "/private/tmp/trinity-20191114-41443-1auzdsk/trinityrnaseq-Trinity-v2.8.3/trinity-plugins/ParaFly-0.1.0/bin"
>make[4]: Nothing to be done for `install-data-am'.
>  /usr/bin/install -c ParaFly '/private/tmp/trinity-20191114-41443-1auzdsk/trinityrnaseq-Trinity-v2.8.3/trinity-plugins/ParaFly-0.1.0/bin'
>make[4]: Nothing to be done for `install-exec-am'.
>make[4]: Nothing to be done for `install-data-am'.

At this point I'm at a bit of a loss. This error has followed me across two computers and everything I have tried has failed.

`brew gist-logs trinity` yelled at me about Keychain despite entering the correct password and subsequently trying to set up a personal access token, so see the outputs below for info on the state of my Homebrew install.

**`brew config` output**
>HOMEBREW_VERSION: 2.1.16
>ORIGIN: https://github.com/Homebrew/brew
>HEAD: 3aa7624284c43180a3f3a71aeaa9263092868e12
>Last commit: 9 days ago
>Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
>Core tap HEAD: c8286d727df784a6a442bc7ddd202e3cdaafd45d
>Core tap last commit: 26 minutes ago
>HOMEBREW_PREFIX: /usr/local
>CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 10.0 build 1001
Git: 2.24.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_144
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: N/A
CLT headers: 10.3.0.0.1.1562985497

**`brew doctor` output**
>Warning: "config" scripts exist outside your system or Homebrew directories.
>`./configure` scripts often look for *-config scripts to determine if
>software packages are installed, and which additional flags to use when
>compiling and linking.
>
>Having additional scripts in your path can confuse software installed via
>Homebrew if the config script overrides a system or Homebrew-provided
>script of the same name. We found the following "config" scripts:
>  /Users/venomlab/anaconda2/bin/llvm-config
>  /Users/venomlab/anaconda2/bin/python2-config
>  /Users/venomlab/anaconda2/bin/icu-config
>  /Users/venomlab/anaconda2/bin/krb5-config
>  /Users/venomlab/anaconda2/bin/freetype-config
>  /Users/venomlab/anaconda2/bin/xslt-config
>  /Users/venomlab/anaconda2/bin/libpng16-config
>  /Users/venomlab/anaconda2/bin/python2.7-config
>  /Users/venomlab/anaconda2/bin/libpng-config
>  /Users/venomlab/anaconda2/bin/xml2-config
>  /Users/venomlab/anaconda2/bin/python-config
>  /Users/venomlab/anaconda2/bin/curl-config
>  /Users/venomlab/anaconda2/bin/ncursesw6-config
>  /Users/venomlab/anaconda2/bin/pcre-config

**Comment by jonchang** [comment]
looks like trinity depends on express which depends on protobuf@3.1 which no longer exists. the express formula will likely have to vendor protobuf 3.1 as upstream is no longer updating it.

**Comment by jonchang** [comment]
This was probably fixed by https://github.com/brewsci/homebrew-bio/pull/833
