### ISSUE TITLE
installing EMBOSS erorr

### ISSUE THREAD

**Issue by bioinfo-Kacst** [brewsci/homebrew-bio#844]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:

- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new or https://github.com/Linuxbrew/brew/issues/new.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
HOMEBREW_VERSION: 2.2.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7d7de295dfbc5e581106e2b1f674496b5e25a773
Last commit: 11 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: b157661a278ce9da6394ceb9dc0730e939c7785d
Core tap last commit: 59 minutes ago
HOMEBREW_PREFIX: /lustre/mohanad/.linuxbrew
HOMEBREW_CELLAR: /lustre/mohanad/.linuxbrew/Cellar
HOMEBREW_CACHE: /lustre/mohanad/.cache/Homebrew
HOMEBREW_LOGS: /lustre/mohanad/.cache/Homebrew/Logs
HOMEBREW_REPOSITORY: /lustre/mohanad/.linuxbrew/Homebrew
HOMEBREW_BUILD_FROM_SOURCE: 1
HOMEBREW_SYSTEM_CURL_TOO_OLD: 1
CPU: 16-core 64-bit broadwell
Homebrew Ruby: 2.6.3 => /lustre/mohanad/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: N/A
Git: 2.24.0 => /lustre/mohanad/.linuxbrew/bin/git
Curl: 7.67.0 => /lustre/mohanad/.linuxbrew/opt/curl/bin/curl
Kernel: Linux 3.10.0-327.el7.x86_64 x86_64 GNU/Linux
OS: CentOS Linux release 7.2.1511 (Core)  (Core)
Host glibc: 2.17
/usr/bin/gcc: 4.8.5
glibc: 2.23
gcc: 5.5.0_7
xorg: N/A

To help us debug your issue please explain:

- What you were trying to do (and why)
trying to install Emboss package to use getorf 
- What happened (include command output)
```
==> Installing emboss from brewsci/bio
==> Downloading ftp://emboss.open-bio.org/pub/EMBOSS/EMBOSS-6.6.0.tar.gz
Already downloaded: /lustre/mohanad/.cache/Homebrew/downloads/96cd20fa32c7065e96a813ca62f2bc652fee9061a40baf7481571b6f7feea0fb--EMBOSS-6.6.0.tar.gz
==> ./configure --prefix=/lustre/mohanad/.linuxbrew/Cellar/emboss/6.6.0 --mandir=/lustre/mohanad/.linuxbrew/Cellar/emboss/6.6.0/share/man --docdir=/lustre/mohanad/.linuxbrew/Cellar/emboss/6.6.0/share/doc/emboss --enable-64 --with-thread --without-x
==> make install
Last 15 lines from /lustre/mohanad/.cache/Homebrew/Logs/emboss/02.make:
make[2]: Nothing to be done for `install-data-am'.
make[3]: Entering directory `/tmp/emboss-20191210-2599-t7bt36/EMBOSS-6.6.0'
/lustre/mohanad/.linuxbrew/Cellar/emboss/6.6.0/bin/embossupdate
Check for more recent updates to EMBOSS
Error: [Temporary failure in name resolution] Failed to find host 'emboss.open-bio.org' for database 'EMBOSSupdates'
Error: ajHttpRead: cannot open HTTP connection 'http://emboss.open-bio.org/updates/EMBOSS.fixes'
Died: Failed to read 'http://emboss.open-bio.org/updates/EMBOSS.fixes'
EMBOSS release 6.6.0.0: update information not available
make[3]: *** [install-exec-hook] Error 1
make[3]: Leaving directory `/tmp/emboss-20191210-2599-t7bt36/EMBOSS-6.6.0'
make[2]: *** [install-exec-am] Error 2
make[2]: Leaving directory `/tmp/emboss-20191210-2599-t7bt36/EMBOSS-6.6.0'
make[1]: *** [install-am] Error 2
make[1]: Leaving directory `/tmp/emboss-20191210-2599-t7bt36/EMBOSS-6.6.0'
make: *** [install-recursive] Error 1
```

# Formula additions or changes

To get formulae added or changed in Brewsci/bio please file a [Pull Request](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md).

**Comment by sjackman** [comment]
Consider installing Linuxbrew in `/home/linuxbrew/.linuxbrew/` if possible so that you can use precompiled binary packages (known as bottles) for non-relocatable formula like `util-linux`.
Another possible workaround for you is `brew install --force-bottle util-linux`, but no promises.

If it's an option for you, you could open a ticket with your information systems department to ask that they create a `linuxbrew` role account with home directory `/home/linuxbrew`.

The precompiled binary bottles of non-relocatable bottles can only be used if you install in `/home/linuxbrew/.linuxbrew`, otherwise they have to be built from source. See the documentation below. On macOS the default installation directory is `/usr/local`. On Linux the default installation directory is `/home/linuxbrew/.linuxbrew`.

+ http://docs.brew.sh/Installation.html#alternative-installs
+ http://docs.brew.sh/FAQ.html#why-do-you-compile-everything
+ http://docs.brew.sh/Bottles.html#cellar-cellar

**Comment by sjackman** [comment]
```
Error: [Temporary failure in name resolution] Failed to find host 'emboss.open-bio.org' for database 'EMBOSSupdates'
```
That looks like a transient error. It may work if you try the same installation again.
