### ISSUE TITLE
Failing action added to forked repository

### ISSUE THREAD

**Issue by heuermh** [brewsci/homebrew-bio#861]
After merging my fork with upstream and pushing, I have a failed Github Action

https://github.com/heuermh/homebrew-bio/actions

Is it possible to turn these off?  Or is there something I need to do to make it work?  It doesn't seem quite right to me that actions should automatically be inherited by forked Github repositories.

**Comment by sjackman** [comment]
Probably? I'm not GitHub Actions expert (yet).
```
fatal: 'origin/gh-pages' is not a commit and a branch 'gh-pages' cannot be created from it
```
The easiest workaround for now is to push the `gh-pages` from this repo to your repo.

**Comment by sjackman** [comment]
Closing this question, but feel free to follow up.
